export const educationSections = [
  'editions',
  'practice',
  'scoring',
  'tools',
  'reflection',
  'backup',
] as const;

export const guides = [
  {
    id: 'json',
    route: '/engineering/json',
    group: 'engineering',
    title: 'engineering.json',
  },
  {
    id: 'diff',
    route: '/engineering/compare',
    group: 'engineering',
    title: 'engineering.diff',
  },
  {
    id: 'sql',
    route: '/engineering/sql',
    group: 'engineering',
    title: 'engineering.sql',
  },
  {
    id: 'encoding',
    route: '/engineering/encoding',
    group: 'engineering',
    title: 'engineering.encoding',
  },
  {
    id: 'regex',
    route: '/engineering/regex',
    group: 'engineering',
    title: 'engineering.regex',
  },
  {
    id: 'knowledge',
    route: '/engineering/knowledge',
    group: 'engineering',
    title: 'engineering.knowledge',
  },
  {
    id: 'cron',
    route: '/engineering/cron',
    group: 'engineering',
    title: 'engineering.cron',
  },
  {
    id: 'prompt',
    route: '/ai-engineering/prompt',
    group: 'ai',
    title: 'ai.prompt',
  },
  {
    id: 'cost',
    route: '/ai-engineering/cost',
    group: 'ai',
    title: 'ai.cost',
  },
  {
    id: 'workflow',
    route: '/ai-engineering/workflow',
    group: 'ai',
    title: 'ai.workflow',
  },
  {
    id: 'mortgage',
    route: '/life-tools/mortgage',
    group: 'life',
    title: 'tools.menu.mortgage',
  },
  {
    id: 'tax',
    route: '/life-tools/income-tax',
    group: 'life',
    title: 'tools.menu.tax',
  },
  {
    id: 'dates',
    route: '/life-tools/dates',
    group: 'life',
    title: 'dates.title',
  },
  {
    id: 'education',
    route: '/education',
    group: 'education',
    title: 'education.title',
  },
  {
    id: 'game',
    route: '/entertainment/magic-bottles',
    group: 'entertainment',
    title: 'tools.menu.game',
  },
  {
    id: 'calendar',
    route: '/finance/calendar',
    group: 'finance',
    title: 'investmentCalendar.titlePage',
  },
  {
    id: 'status',
    route: '/finance/data-status',
    group: 'finance',
    title: 'dataStatus.title',
  },
  {
    id: 'portfolio',
    route: '/finance/portfolio',
    group: 'finance',
    title: 'finance.menu.portfolio',
  },
  {
    id: 'wishlist',
    route: '/finance/wishlist',
    group: 'finance',
    title: 'wishlist.title',
  },
  {
    id: 'etf',
    route: '/finance/etf-comparison',
    group: 'finance',
    title: 'finance.menu.etf',
  },
  {
    id: 'guide',
    route: '/usage-guide',
    group: 'guide',
    title: 'guide.title',
  },
];
export const groups = [
  'engineering',
  'ai',
  'life',
  'education',
  'entertainment',
  'finance',
  'guide',
];
export const articleFields = [
  'summary',
  'step1',
  'step2',
  'step3',
  'step4',
  'example',
  'note',
] as const;
