export const bnuLowerWrittenAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10763.html',
  checkedAt: '2026-10-05',
  unit: 'u5',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope: '68～69全部六原活动对应；70页起后续、整册全年与最终教师试用未核验。',
  activities: [
    {
      page: 68,
      sourceActivity: 'rods-read-addition-and-places',
      lesson: 'bnu-lower-written',
      steps: [1],
      objective: ['rod-add-values', 'rod-add-digits', 'rod-orientation'],
      manual: ['actual-rods-add'],
      records: [],
    },
    {
      page: 68,
      sourceActivity: 'written-addition-stages-and-alignment',
      lesson: 'bnu-lower-written',
      steps: [2, 3],
      objective: [
        'add-ones',
        'add-missing-tens',
        'add-stage-meaning',
        'add-tens',
        'add-complete',
        'alignment',
      ],
      manual: ['actual-add-stage', 'actual-add-final'],
      records: ['method-record'],
    },
    {
      page: 69,
      sourceActivity: 'subtraction-rods-counter-written',
      lesson: 'bnu-lower-written',
      steps: [4, 5, 6],
      objective: [
        'rod-sub-values',
        'sub-counter-digits',
        'sub-beads',
        'sub-ones',
        'sub-tens',
        'sub-blanks',
      ],
      manual: ['actual-rods-sub', 'actual-counter-sub', 'actual-sub-written'],
      records: [],
    },
    {
      page: 69,
      sourceActivity: 'both-cross-matches',
      lesson: 'bnu-lower-written',
      steps: [7],
      objective: ['matching-a', 'matching-b', 'matching-values'],
      manual: ['actual-matches'],
      records: [],
    },
    {
      page: 69,
      sourceActivity: 'all-four-written-calculations',
      lesson: 'bnu-lower-written',
      steps: [8, 10],
      objective: ['practice-digits', 'practice-results', 'site-zero'],
      manual: [
        'actual-practice-1',
        'actual-practice-2',
        'actual-practice-3',
        'actual-practice-4',
      ],
      records: ['own-record', 'plan'],
    },
    {
      page: 69,
      sourceActivity: 'one-bottle-per-person-remaining',
      lesson: 'bnu-lower-written',
      steps: [9],
      objective: ['water-conditions', 'water-result', 'water-unit'],
      manual: ['actual-water'],
      records: [],
    },
  ],
} as const;
