export const bnuLowerBreedingAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10762.html',
  checkedAt: '2026-10-05',
  unit: 'u4',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅52～53页七原活动及明确的新条件；54页起仍制作，不证明整个单元或全年。',
  activities: [
    {
      page: 52,
      sourceActivity: 'observe-three',
      lesson: 'bnu-lower-breeding',
      steps: [1],
      objective: [
        'given-counts',
        'most-three',
        'least-three',
        'rabbit-unknown',
        'picture-count',
      ],
      manual: ['actual-observe'],
      records: [],
      boundary: '标签与画中件数分清，兔尚未知不入三种已知最多最少，不补0。',
    },
    {
      page: 52,
      sourceActivity: 'line-and-language',
      lesson: 'bnu-lower-breeding',
      steps: [2],
      objective: [
        'hen-goose',
        'hen-duck',
        'duck-hen',
        'goose-hen',
        'close-hen-duck',
        'line-right',
        'threshold',
      ],
      manual: ['actual-language'],
      records: [],
      boundary:
        '四方向与接近表达完整，网站补0刻度明示，标签错行不改变横线点位置。',
    },
    {
      page: 52,
      sourceActivity: 'sheep-candidates',
      lesson: 'bnu-lower-breeding',
      steps: [3],
      objective: ['sheep-choice', 'sheep-actual'],
      manual: ['actual-sheep'],
      records: [],
      boundary: '候选与22作情境比较，不冒真实点数或新通用阈值。',
    },
    {
      page: 53,
      sourceActivity: 'rabbit-clues',
      lesson: 'bnu-lower-breeding',
      steps: [4],
      objective: [
        'rabbit-candidates',
        'rabbit-two-left',
        'rabbit-before-no',
        'rabbit-final',
        'rabbit-order',
      ],
      manual: ['actual-rabbit'],
      records: [],
      boundary:
        '暂余两个与最终97分别处理，候选及完整回应共同决定，不从原兔图点数猜97。',
    },
    {
      page: 53,
      sourceActivity: 'sort-five',
      lesson: 'bnu-lower-breeding',
      steps: [5],
      objective: [
        'original-cards',
        'sorted-cards',
        'card-count',
        'fifty-fifty-one',
      ],
      manual: ['actual-sort'],
      records: [],
      boundary:
        '原五卡乱序与排序后各完整表示，5张与各卡数值分清，不合并50与51。',
    },
    {
      page: 53,
      sourceActivity: 'two-methods',
      lesson: 'bnu-lower-breeding',
      steps: [6],
      objective: [
        'select-minimum',
        'insert-first-three',
        'insert-all',
        'partial-method',
      ],
      manual: ['actual-minimum-method', 'actual-insert-method'],
      records: [],
      boundary: '两种方法各完整实做五卡，三张中间状态与最终五张分开。',
    },
    {
      page: 53,
      sourceActivity: 'mark-line',
      lesson: 'bnu-lower-breeding',
      steps: [7, 8],
      objective: [
        'marked-direction',
        'near-pair',
        'ninety-eight-between',
        'label-height',
        'site-zero',
      ],
      manual: ['actual-mark', 'actual-explain'],
      records: [
        'own-comparison',
        'own-sort',
        'discovery',
        'difficulty',
        'plan',
      ],
      boundary:
        '原五点与本站补0刻度分清，标签分行仅防重叠；真实标点解释与反思及计划独立。',
    },
  ],
} as const;
