export const bnuLowerUnitSixAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10764.html',
  checkedAt: '2026-10-05',
  unit: 'u6',
  status: 'partial-original-teaching',
  finalTeacherReview: 'not-verified',
  scope:
    '76～77六原活动、43主任务和8换条件复习三宽已验；78～86后续仍制作，保留单元待制作入口。',
  activities: [
    {
      page: 76,
      sourceActivity: 'predict-contact-footprints',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [1],
      objective: ['face', 'unknown-footprint'],
      manual: ['actual-footprint'],
      records: [],
    },
    {
      page: 76,
      sourceActivity: 'trace-faces-and-name-four-shapes',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [2],
      objective: ['face'],
      manual: ['actual-four-traces'],
      records: [],
    },
    {
      page: 77,
      sourceActivity: 'match-all-eleven-and-rotate-square',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [3, 4, 5],
      objective: [
        'row-1',
        'row-2',
        'row-3',
        'row-4',
        'row-5',
        'row-6',
        'row-7',
        'row-8',
        'row-9',
        'row-10',
        'row-11',
        'row-count-rectangle',
        'row-count-square',
        'row-count-circle',
        'row-count-triangle',
        'rotation-category',
        'rotation-count',
      ],
      manual: ['actual-eleven', 'actual-turn'],
      records: [],
    },
    {
      page: 77,
      sourceActivity: 'nearby-object-predict-before-tracing',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [6],
      objective: ['prediction-order'],
      manual: ['actual-predict', 'actual-trace-check'],
      records: ['prediction-record'],
    },
    {
      page: 77,
      sourceActivity: 'color-boat-and-rocket-by-four-shape-legend',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [7, 8],
      objective: [
        'color-triangle',
        'color-circle',
        'color-rectangle',
        'color-square',
        'open-lines',
      ],
      manual: ['actual-boat', 'actual-rocket'],
      records: [],
    },
    {
      page: 77,
      sourceActivity: 'count-train-four-categories',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [9, 10],
      objective: [
        'train-square',
        'train-triangle',
        'train-rectangle',
        'train-circle',
        'open-lines',
        'site-zero',
      ],
      manual: ['actual-train', 'actual-share'],
      records: ['reflection', 'plan'],
    },
  ],
  pendingPrintedPages: [78, 79, 80, 81, 82, 83, 84, 85, 86],
} as const;
