/** Independent source-to-task mapping for printed pages 27–28 only. */
export const bnuLowerPencilsAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10761.html',
  checkedAt: '2026-10-05',
  unit: 'u3',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅印刷27～28页买铅笔与练习的活动及明示附加过程对应；第29页起第三单元后续仍制作中，不证明整单元、全册或全年完成。',
  activities: [
    {
      page: 27,
      sourceActivity: 'read-information',
      scope: '四条文具信息及对象单位',
      lesson: 'bnu-lower-buy-pencils',
      steps: [1],
      objective: [
        'pencils-original',
        'pencils-bought',
        'notebooks-original',
        'notebooks-bought',
        'units',
      ],
      manual: ['actual-info'],
      records: [],
      boundary: '支与本分开，不混用练习本9本求剩余铅笔。',
    },
    {
      page: 27,
      sourceActivity: 'one-by-one',
      scope: '逐根减与铅笔剩余',
      lesson: 'bnu-lower-buy-pencils',
      steps: [2],
      objective: ['pencils-left', 'one-by-one'],
      manual: ['actual-one-by-one'],
      records: [],
      boundary: '起点12不是第一步结果；明确逐根取七次，原图与本站过程分开。',
    },
    {
      page: 27,
      sourceActivity: 'break-ten',
      scope: '拆原有12为10和2',
      lesson: 'bnu-lower-buy-pencils',
      steps: [3],
      objective: ['break-ten', 'split-object'],
      manual: ['actual-break-ten'],
      records: [],
      boundary: '只从10取7，未动2与3合并，不把7拆10与2。',
    },
    {
      page: 27,
      sourceActivity: 'subtract-parts',
      scope: '减去7拆2和5',
      lesson: 'bnu-lower-buy-pencils',
      steps: [4],
      objective: ['subtract-parts'],
      manual: ['actual-subtract-parts'],
      records: [],
      boundary: '指定先到10不是唯一正确算法，两次取走合7。',
    },
    {
      page: 27,
      sourceActivity: 'think-add',
      scope: '7补到12与减法',
      lesson: 'bnu-lower-buy-pencils',
      steps: [5],
      objective: ['think-add'],
      manual: ['actual-think-add'],
      records: [],
      boundary: '缺少量5与故事剩余对应，不冒另买5支。',
    },
    {
      page: 28,
      sourceActivity: 'notebooks',
      scope: '15本买9本求剩余',
      lesson: 'bnu-lower-buy-pencils',
      steps: [6],
      objective: ['notebooks-left', 'notebooks-parts', 'notebooks-break'],
      manual: ['actual-notebooks'],
      records: [],
      boundary: '原有15拆10与5、减数9拆5与4分别问；本站追加过程明确指定。',
    },
    {
      page: 28,
      sourceActivity: 'practice-one',
      scope: '摆棒11减5与16减8',
      lesson: 'bnu-lower-buy-pencils',
      steps: [6],
      objective: ['sticks-11-5', 'sticks-16-8'],
      manual: ['actual-sticks'],
      records: [],
      boundary: '两式全部覆盖，网页结果不确认实际摆棒。',
    },
    {
      page: 28,
      sourceActivity: 'practice-two',
      scope: '两条数线画算',
      lesson: 'bnu-lower-buy-pencils',
      steps: [7],
      objective: ['line-12-4', 'line-15-7', 'line-first', 'line-parts'],
      manual: ['actual-lines'],
      records: [],
      boundary: '起点方向和相邻间隔分清，两原路径实际画记独立。',
    },
    {
      page: 28,
      sourceActivity: 'practice-three',
      scope: '9与5星图一加两减',
      lesson: 'bnu-lower-buy-pencils',
      steps: [8],
      objective: ['star-add', 'star-remove-nine', 'star-remove-five'],
      manual: ['actual-stars'],
      records: [],
      boundary: '整体14与两部分9和5分清，不复制原星形插图。',
    },
    {
      page: 28,
      sourceActivity: 'practice-four',
      scope: '17原有9剩余求吃掉',
      lesson: 'bnu-lower-buy-pencils',
      steps: [9],
      objective: ['pine-eaten', 'pine-check', 'pine-meaning'],
      manual: ['actual-pine'],
      records: [],
      boundary: '给定剩余9不当吃掉9，17减9得8，单位个。',
    },
    {
      page: 28,
      sourceActivity: 'explain-and-reflect',
      scope: '原说摆算与本站方法反思计划',
      lesson: 'bnu-lower-buy-pencils',
      steps: [9],
      objective: [],
      manual: ['actual-explain'],
      records: ['my-method', 'plan'],
      boundary:
        '口述实际确认、反思和未来计划独立，correct:null，不自动确认实做。',
    },
  ],
} as const;
