export const bnuLowerAroundNumbersAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10762.html',
  checkedAt: '2026-10-05',
  unit: 'u4',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅44～45页身边的数七项原活动及明示迁移，46页起仍制作；不证明整个第四单元、全册、全年或最终教师审校。',
  activities: [
    {
      page: 44,
      sourceActivity: 'compare-before-count',
      lesson: 'bnu-lower-around-numbers',
      steps: [1],
      objective: ['pile', 'unknown-pile'],
      manual: ['actual-discussion'],
      records: [],
      boundary: '不从堆大小或未核定散放图猜总数，不借其它对象62。',
    },
    {
      page: 44,
      sourceActivity: 'one-by-one',
      lesson: 'bnu-lower-around-numbers',
      steps: [2],
      objective: ['after-twenty', 'after-twenty-nine', 'new-start'],
      manual: ['actual-one'],
      records: [],
      boundary: '原20/29接点完整与本站28新起点分开；整批逐物实际数另做。',
    },
    {
      page: 44,
      sourceActivity: 'check-count',
      lesson: 'bnu-lower-around-numbers',
      steps: [3],
      objective: [
        'group-twos',
        'group-fives',
        'odd-pair',
        'zero-remainder',
        'keep-remainder',
      ],
      manual: ['actual-two', 'actual-five', 'actual-recheck'],
      records: [],
      boundary:
        '原三种重新数实际分别覆盖；本站62/65分组明示，余数不漏、确定0不未知，不引入除法。',
    },
    {
      page: 45,
      sourceActivity: 'represent-circles',
      lesson: 'bnu-lower-around-numbers',
      steps: [4],
      objective: ['circle-count', 'circle-rows', 'circle-meaning'],
      manual: ['actual-circles', 'actual-own-circles'],
      records: ['own-circle-record'],
      boundary:
        '原六行各十加二，每圆一为62；本站图为等价原创，自己真实数量开放。',
    },
    {
      page: 45,
      sourceActivity: 'represent-triangles',
      lesson: 'bnu-lower-around-numbers',
      steps: [5],
      objective: [
        'triangle-markers',
        'triangle-value',
        'triangle-convention',
        'changed-convention',
        'triangle-groups',
      ],
      manual: ['actual-triangles', 'actual-own-symbols'],
      records: ['own-symbol-record'],
      boundary:
        '七大五小12图标与原话75分清，大十小一明示约定，换每图标一为12。',
    },
    {
      page: 45,
      sourceActivity: 'numbers-around',
      lesson: 'bnu-lower-around-numbers',
      steps: [6],
      objective: [
        'life-numbers',
        'life-units',
        'rounds',
        'future-round',
        'own-class',
      ],
      manual: ['actual-life-source', 'actual-own-life'],
      records: [],
      boundary:
        '全部四例五数及各单位完整，原班不自家，已有两轮不保证未来，不强加和差。',
    },
    {
      page: 45,
      sourceActivity: 'own-question',
      lesson: 'bnu-lower-around-numbers',
      steps: [7, 8],
      objective: [
        'plan-or-actual',
        'own-total',
        'zero-box',
        'unknown-box',
        'method-choice',
      ],
      manual: ['actual-question', 'actual-investigation', 'actual-exchange'],
      records: [
        'own-question',
        'own-result',
        'own-plan',
        'discovery',
        'difficulty',
        'next-plan',
      ],
      boundary:
        '原自主问题开放，新增回顾迁移明示；自己的已做/未做/未来计划分记，没查不0，不采学校个人信息。',
    },
  ],
} as const;
