/** Source facts only. Reading a page does not release its teaching package. */
export const bnuLowerRecognizeShapesSource = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10764.html',
  checkedAt: '2026-10-05',
  status: 'source-checked',
  readPrintedPages: [76, 77],
  pageImages: [
    { printedPage: 76, suffix: '080.jpg' },
    { printedPage: 77, suffix: '081.jpg' },
  ],
  title: '认识图形',
  unit: '有趣的平面图形（一）',
  categories: ['rectangle', 'square', 'circle', 'triangle'],
  footprints: {
    blueCube: 'square',
    purpleObject: 'choose-and-check-the-contact-face',
    boundary:
      '立体物体与选定接触面的平面轮廓不同；紫色物体底面不能只按颜色或正面透视猜。圆柱平整底面可描圆，曲面、球和实际滚印另核对。',
  },
  matching: {
    readingOrder: 'left-to-right',
    shapes: [
      'rectangle',
      'triangle',
      'circle',
      'square',
      'circle',
      'square',
      'triangle',
      'rectangle',
      'rectangle',
      'triangle',
      'square',
    ],
    alreadyConnectedPositions: [1],
    rotatedRectanglePosition: 8,
    uprightRectanglePosition: 9,
    rotatedSquarePosition: 11,
    rotationDialogueCategory: 'square',
    counts: { rectangle: 3, square: 3, circle: 2, triangle: 3 },
    boundary:
      '最后斜放图对应正方形，不误录长方形；11个全部匹配，包括原已示范第1个。大小、转向不改变类别，沿一年级本题四类分别归组，不将正方形另重计为长方形。',
  },
  coloring: {
    legend: {
      triangle: 'red',
      circle: 'green',
      rectangle: 'blue',
      square: 'yellow',
    },
    knownRegions: [
      { key: 'boat-flag', shape: 'triangle' },
      { key: 'boat-small-cabin', shape: 'square' },
      { key: 'boat-large-cabin', shape: 'rectangle' },
      { key: 'boat-porthole-1', shape: 'circle' },
      { key: 'boat-porthole-2', shape: 'circle' },
      { key: 'boat-porthole-3', shape: 'circle' },
      { key: 'boat-porthole-4', shape: 'circle' },
      { key: 'boat-window-1', shape: 'rectangle' },
      { key: 'boat-window-2', shape: 'rectangle' },
      { key: 'boat-window-3', shape: 'rectangle' },
      { key: 'boat-window-4', shape: 'rectangle' },
      { key: 'rocket-nose', shape: 'triangle' },
      { key: 'rocket-upper-panel', shape: 'square' },
      { key: 'rocket-middle-panel', shape: 'rectangle' },
      { key: 'rocket-lower-panel', shape: 'square' },
      { key: 'rocket-left-fin', shape: 'triangle' },
      { key: 'rocket-right-fin', shape: 'triangle' },
    ],
    excluded: [
      'flag-pole-open-line',
      'boat-deck-surrounding-circles',
      'boat-hull-surrounding-windows',
    ],
    boundary:
      '图例是原题指定配色，不跟项目主题色改变；17项是已识别四类区域，不是原图所有白色区域总数。旗杆不是闭合面，船甲板与船身剩余外轮廓带斜边且含内圈/窗口，不能整体强说长方形或补造未画分割线。涂色仍按原书完整区域实际完成，不用四个图例选择题代替。',
  },
  train: {
    confirmedParts: [
      { key: 'wagon-1', shape: 'rectangle' },
      { key: 'wagon-2', shape: 'rectangle' },
      { key: 'wagon-3', shape: 'rectangle' },
      { key: 'engine-base', shape: 'rectangle' },
      { key: 'engine-roof', shape: 'rectangle' },
      { key: 'engine-cab', shape: 'square' },
      { key: 'engine-front', shape: 'triangle' },
      { key: 'wheel-1', shape: 'circle' },
      { key: 'wheel-2', shape: 'circle' },
      { key: 'wheel-3', shape: 'circle' },
      { key: 'wheel-4', shape: 'circle' },
      { key: 'wheel-5', shape: 'circle' },
      { key: 'wheel-6', shape: 'circle' },
      { key: 'wheel-7', shape: 'circle' },
      { key: 'wheel-8', shape: 'circle' },
    ],
    confirmedCounts: { square: 1, triangle: 1, rectangle: 5, circle: 8 },
    excluded: ['smoke-open-lines', 'slanted-blue-chimney'],
    boundary:
      '三节车厢加车头底座与顶横条为五长方形，驾驶室方形、前部三角形、八圆轮逐个对应。蓝烟囱上边斜且内部有斜线，不从烟囱名称猜长方形，不凭颜色填基本类别；烟雾开放曲线不是圆。数已画基本部件，不把外接框、画面叠合或自行延长线造出的轮廓再加为部件。原书全部四空与实际指认仍须完成，来源阅读不自动等于课程发布。',
  },
  activities: [
    { page: 76, key: 'predict-contact-footprints' },
    { page: 76, key: 'trace-faces-and-name-four-shapes' },
    { page: 77, key: 'match-all-eleven-and-rotate-square' },
    { page: 77, key: 'nearby-object-predict-before-tracing' },
    { page: 77, key: 'color-boat-and-rocket-by-four-shape-legend' },
    { page: 77, key: 'count-train-four-categories' },
  ],
  boundary:
    '六原活动分别对应实际预测、描面、全连线、实物先想后描、完整两图涂色与四类计数；不复制未经授权教材原图。原创同类示意与原书轮廓/实物尺寸分清，已看网页不作实做确认。开放发现和未来计划各null，不自动评星；第三方来源与未知ISBN/版印如实，来源已核对不代表第六单元或整册已完成。',
} as const;
