/** All eight original activities on pages 42–43, distinct from teacher review. */
export const bnuLowerSubtractionPracticeAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10761.html',
  checkedAt: '2026-10-05',
  unit: 'u3',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '第42～43页完整巩固应用及明示迁移，原自主题开放；不证明全册、全年或最终教师审校。',
  activities: [
    {
      page: 42,
      sourceActivity: 'circle',
      lesson: 'bnu-lower-subtraction-practice',
      steps: [1],
      objective: ['mushrooms', 'peppers', 'circle-meaning'],
      manual: ['actual-mushrooms', 'actual-peppers'],
      records: [],
      boundary: '两原图圈内8/9与剩余5/6分清，圈线不增物。',
    },
    {
      page: 42,
      sourceActivity: 'number-line',
      lesson: 'bnu-lower-subtraction-practice',
      steps: [2],
      objective: ['line-to-ten', 'line-each'],
      manual: ['actual-line'],
      records: [],
      boundary: '18为起点，九个落点完整；原合理画法开放，本站两示例明示。',
    },
    {
      page: 42,
      sourceActivity: 'calculations',
      lesson: 'bnu-lower-subtraction-practice',
      steps: [3],
      objective: ['row-one', 'row-two', 'row-three'],
      manual: ['actual-calculations'],
      records: [],
      boundary: '原十二式按三行各四完整算，不以少量示例替代。',
    },
    {
      page: 42,
      sourceActivity: 'furniture',
      lesson: 'bnu-lower-subtraction-practice',
      steps: [4],
      objective: [
        'furniture',
        'furniture-unit',
        'zero-missing',
        'unknown-furniture',
      ],
      manual: ['actual-furniture'],
      records: [],
      boundary: '原14椅9桌缺5张；本站完整0与新未知条件分开。',
    },
    {
      page: 42,
      sourceActivity: 'own-kicks',
      lesson: 'bnu-lower-subtraction-practice',
      steps: [5],
      objective: [
        'kicks-counts',
        'kicks-total-example',
        'kicks-difference-example',
      ],
      manual: ['actual-kicks-one', 'actual-kicks-two'],
      records: ['own-kicks-one', 'own-kicks-two'],
      boundary: '原5/7/13两自主问均独立实际与记录，本站例子不作唯一问题。',
    },
    {
      page: 43,
      sourceActivity: 'families',
      lesson: 'bnu-lower-subtraction-practice',
      steps: [6],
      objective: [
        'family-fourteen',
        'family-twelve',
        'family-thirteen',
        'family-order',
      ],
      manual: [
        'actual-family-fourteen',
        'actual-family-twelve',
        'actual-family-thirteen',
      ],
      records: [],
      boundary:
        '三组各完整四式，原两加/两减顺序可交换，本站客观排列不冒唯一纸面填法。',
    },
    {
      page: 43,
      sourceActivity: 'animals',
      lesson: 'bnu-lower-subtraction-practice',
      steps: [7],
      objective: [
        'animals-counts',
        'animals-difference',
        'animals-addition',
        'unknown-animals',
      ],
      manual: [
        'actual-animal-counts',
        'actual-animal-relations',
        'actual-animal-question',
      ],
      records: ['own-animal-question'],
      boundary:
        '三图标10/6/2、差4/合12和再一问分别覆盖，钳子不增物、小壳不冒乌龟。',
    },
    {
      page: 43,
      sourceActivity: 'free-equations',
      lesson: 'bnu-lower-subtraction-practice',
      steps: [8],
      objective: [
        'free-add-twelve',
        'free-subtract-twelve',
        'free-add-fourteen',
        'free-subtract-fourteen',
      ],
      manual: ['actual-free-twelve', 'actual-free-fourteen', 'actual-exchange'],
      records: ['discovery', 'difficulty', 'plan'],
      boundary:
        '原六槽完整纸写且更多可继续，网页0～20组合全合法解；有限四网页题不自动确认真实六槽。',
    },
  ],
} as const;
