export const bnuLowerFillGameAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10762.html',
  checkedAt: '2026-10-05',
  unit: 'games',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '印刷60～61页五项活动、原3×3五空/5×5七空及两个中间阶段完整对应；无额外宫格/对角线规则，真实纸面与交流另记，不证明全年或最终教师审校完成。',
  activities: [
    {
      page: 60,
      sourceActivity: 'understand-row-column-rule',
      lesson: 'bnu-lower-fill-game',
      steps: [1],
      objective: ['allowed-three', 'row-repeat', 'column-repeat', 'diagonal'],
      manual: ['actual-rule'],
      records: [],
    },
    {
      page: 60,
      sourceActivity: 'three-complete-grid',
      lesson: 'bnu-lower-fill-game',
      steps: [2, 3],
      objective: ['three-start', 'three-all', 'three-bottom', 'three-check'],
      manual: ['actual-three'],
      records: [],
    },
    {
      page: 61,
      sourceActivity: 'five-upgrade-grid',
      lesson: 'bnu-lower-fill-game',
      steps: [4, 5, 7],
      objective: ['five-allowed', 'five-single', 'five-all', 'row-two'],
      manual: ['actual-five'],
      records: [],
    },
    {
      page: 61,
      sourceActivity: 'intermediate-and-both-constraints',
      lesson: 'bnu-lower-fill-game',
      steps: [5, 6, 7],
      objective: [
        'row-options',
        'column-known',
        'intersection',
        'five-next-all',
        'row-only-mistake',
      ],
      manual: ['actual-stage'],
      records: [],
    },
    {
      page: 61,
      sourceActivity: 'review-method-and-real-check',
      lesson: 'bnu-lower-fill-game',
      steps: [8],
      objective: ['givens', 'trial-adjust', 'final-check'],
      manual: ['actual-check', 'actual-exchange'],
      records: ['method', 'trial-record', 'plan'],
    },
  ],
} as const;
