/** Printed source activities mapped to stable teaching tasks; source artwork is not bundled. */
export const bnuLowerUnitOneAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10759.html',
  checkedAt: '2026-10-05',
  unit: 'u1',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '印刷第2～17页第一单元全部所列活动及注明的迁移；只证明源活动与原创教学的对应，不证明后续单元、全册、全年或真实活动完成。',
  activities: [
    {
      page: 2,
      sourceActivity: 'sheep-correspondence',
      scope: '逐只羊对应一根小棒、完整数11',
      lesson: 'bnu-lower-ancient-count-one',
      steps: [1],
      objective: ['one-to-one'],
      manual: ['actual-correspond'],
      records: [],
      boundary: '一根对应一只；原羊群实际点数与网页条件答题分别记录。',
    },
    {
      page: 2,
      sourceActivity: 'bundle-ten',
      scope: '捆十、11/19/20的十与一组成',
      lesson: 'bnu-lower-ancient-count-one',
      steps: [2, 3, 4],
      objective: [
        'bundle',
        'eleven',
        'nineteen',
        'twenty',
        'bundle-unit',
        'zero-ones',
      ],
      manual: [
        'actual-bundle',
        'actual-eleven',
        'actual-nineteen',
        'actual-twenty',
      ],
      records: [],
      boundary:
        '根数和捆数分开，整十散根0合法；zero-ones是明确凑整十的补充条件。',
    },
    {
      page: 3,
      sourceActivity: 'symbols',
      scope: '大/小石头与圈记的意义约定',
      lesson: 'bnu-lower-ancient-count-one',
      steps: [5],
      objective: ['symbol-twelve', 'symbol-fifteen', 'unknown-symbol'],
      manual: ['actual-symbol'],
      records: [],
      boundary:
        '先约定大记10、小记1；材料大小本身不天然决定数值，网页12/15是约定后的迁移。',
    },
    {
      page: 3,
      sourceActivity: 'circle-ten-groups',
      scope: '三组蔬果圈十与接着数：12/13/17',
      lesson: 'bnu-lower-ancient-count-one',
      steps: [6],
      objective: [
        'source-count-strawberries',
        'source-parts-strawberries',
        'source-count-carrots',
        'source-parts-carrots',
        'source-count-cabbages',
        'source-parts-cabbages',
      ],
      manual: ['actual-three-groups'],
      records: [],
      boundary:
        '三组各自计数；首过程空问十内单个数量10而非组数1，实际原图圈点单独确认。',
    },
    {
      page: 3,
      sourceActivity: 'materials',
      scope: '珠串14、单位方块18、小棒16分别计数',
      lesson: 'bnu-lower-ancient-count-one',
      steps: [6],
      objective: [
        'source-count-beads',
        'source-parts-beads',
        'source-count-blocks',
        'source-parts-blocks',
        'source-count-sticks',
        'source-parts-sticks',
      ],
      manual: ['actual-three-materials'],
      records: [],
      boundary:
        '两条10/8单位方块不只算2条，一捆十根加六根不只算7件；十外余量4/8/6。',
    },
    {
      page: 3,
      sourceActivity: 'draw-twelve-fifteen',
      scope: '照约定画12与15的两种数量表示',
      lesson: 'bnu-lower-ancient-count-one',
      steps: [6],
      objective: [],
      manual: ['actual-draw-twelve', 'actual-draw-fifteen'],
      records: [],
      boundary:
        '原书12示例已给大方形1/小方形2；15自行作图，画记件数不等表示值。',
    },
    {
      page: 3,
      sourceActivity: 'knot-story',
      scope: '8只再来3只的结绳计数故事',
      lesson: 'bnu-lower-ancient-count-one',
      steps: [7],
      objective: ['story'],
      manual: ['actual-story'],
      records: ['reflection', 'plan'],
      boundary: '教材计数情境不冒独立历史考证；实际表述、反思与未来计划分记。',
    },
    {
      page: 4,
      sourceActivity: 'same-stones',
      scope: '同样石头标10与1表示11',
      lesson: 'bnu-lower-ancient-count-two',
      steps: [1],
      objective: ['same-material'],
      manual: ['actual-mark'],
      records: [],
      boundary: '同样材料可因标注代表不同单位；未约定时不推定11。',
    },
    {
      page: 4,
      sourceActivity: 'counter-exchange',
      scope: '十位个位、0/9添1到10的换位',
      lesson: 'bnu-lower-ancient-count-two',
      steps: [2, 3],
      objective: ['tens', 'ones', 'ten-zero'],
      manual: ['actual-counter'],
      records: [],
      boundary:
        '18的十位1/个位8为迁移例；原计数器11、0/9/10实际拨画仍独立，个位0不等总量0。',
    },
    {
      page: 4,
      sourceActivity: 'ten-plus',
      scope: '10+1、10+9、10+10三次摆拨填数',
      lesson: 'bnu-lower-ancient-count-two',
      steps: [4],
      objective: ['add-1', 'add-9', 'add-10', 'twenty-tens'],
      manual: ['actual-three-adds'],
      records: [],
      boundary: '十位2表示20，不是20个十；三组各从原10开始，不连续累加。',
    },
    {
      page: 5,
      sourceActivity: 'order-compare',
      scope: '完整9～20数序与12大于9/小于14',
      lesson: 'bnu-lower-ancient-count-two',
      steps: [5],
      objective: [],
      manual: ['actual-number-order'],
      records: [],
      boundary:
        '12>10>9与12/13/14接数两种说明均保留；不能只做后面的四比较替代本活动。',
    },
    {
      page: 5,
      sourceActivity: 'draw-counter',
      scope: '按12/15小棒画计数器及填10+2/5',
      lesson: 'bnu-lower-ancient-count-two',
      steps: [6],
      objective: ['draw-2', 'draw-5'],
      manual: ['actual-draw-twelve', 'actual-draw-fifteen'],
      records: [],
      boundary: '数值作答不代替原数位作图；十位与个位均要标明。',
    },
    {
      page: 5,
      sourceActivity: 'eighteen',
      scope: '18的两种位值表达',
      lesson: 'bnu-lower-ancient-count-two',
      steps: [2, 6],
      objective: [],
      manual: ['actual-eighteen'],
      records: [],
      boundary: '1个十和8个一与十位1/个位8同值；数位标记件数不等18。',
    },
    {
      page: 5,
      sourceActivity: 'clothes-strips',
      scope: '两行衣服数序全部七空',
      lesson: 'bnu-lower-ancient-count-two',
      steps: [6],
      objective: [
        'ascending-0',
        'ascending-1',
        'ascending-2',
        'ascending-3',
        'descending-0',
        'descending-1',
        'descending-2',
      ],
      manual: ['actual-two-strips'],
      records: [],
      boundary: '按给定每次+1和−2；只给有限项不声称所有可能数列唯一。',
    },
    {
      page: 5,
      sourceActivity: 'four-comparisons',
      scope: '13/17、19/9、11/7、10/20逐组比较',
      lesson: 'bnu-lower-ancient-count-two',
      steps: [7],
      objective: [
        'compare-0',
        'compare-1',
        'compare-2',
        'compare-3',
        'compare-4',
      ],
      manual: ['actual-four-comparisons'],
      records: ['reflection', 'plan'],
      boundary: '前四项为原比较，18=18是明确相等迁移；记录不自动确认纸面完成。',
    },
    {
      page: 6,
      sourceActivity: 'blocks-add',
      scope: '13添2的接数、个位计算与整式',
      lesson: 'bnu-lower-building-blocks',
      steps: [1],
      objective: [
        'calc-0',
        'calc-2',
        'calc-3',
        'forward-first',
        'forward-second',
      ],
      manual: ['actual-add'],
      records: [],
      boundary: '先3+2再10+5，同一原13；起点13不算已增加一次。',
    },
    {
      page: 6,
      sourceActivity: 'blocks-subtract',
      scope: '18取2的倒数、个位计算与整式',
      lesson: 'bnu-lower-building-blocks',
      steps: [2],
      objective: [
        'calc-1',
        'calc-4',
        'calc-5',
        'backward-first',
        'backward-second',
      ],
      manual: ['actual-sub'],
      records: [],
      boundary: '先8−2再10+6；不能把原18当第一步取走。',
    },
    {
      page: 7,
      sourceActivity: 'two-number-lines',
      scope: '13+2与18−2两轴每一步说明',
      lesson: 'bnu-lower-building-blocks',
      steps: [3],
      objective: [],
      manual: ['actual-two-jumps'],
      records: [],
      boundary: '每跳一间隔表示1，图线长短不是增加或减少数量。',
    },
    {
      page: 7,
      sourceActivity: 'flowers-pens',
      scope: '花10+3/13−3与笔12+5/17−5四完整式',
      lesson: 'bnu-lower-building-blocks',
      steps: [4],
      objective: ['calc-7', 'calc-8', 'calc-9', 'calc-10', 'zero-ones'],
      manual: ['actual-flowers', 'actual-pens'],
      records: [],
      boundary: '原花单位枝、笔支，网页纸卡张是迁移；散一0不等总量0。',
    },
    {
      page: 7,
      sourceActivity: 'counter-arrow',
      scope: '计数器13向下拨入5得到18及表示区珠数',
      lesson: 'bnu-lower-building-blocks',
      steps: [5],
      objective: [
        'counter-before',
        'counter-added',
        'counter-ten',
        'counter-material-before',
        'counter-material-after',
        'counter-path',
      ],
      manual: ['actual-counter'],
      records: [],
      boundary:
        '待拨入5不算原表示区；原表示区4珠/后9珠，表示值13/18，不称整架材料总数增加。',
    },
    {
      page: 7,
      sourceActivity: 'six-subtract-jumps',
      scope: '19−6六次倒数到13',
      lesson: 'bnu-lower-building-blocks',
      steps: [5],
      objective: ['calc-6'],
      manual: ['actual-six-jumps'],
      records: [],
      boundary: '18/17/16/15/14/13完整六步，不只说终点。',
    },
    {
      page: 7,
      sourceActivity: 'bumper-pairs',
      scope: '四车加法与四车非负减法所有六配对',
      lesson: 'bnu-lower-building-blocks',
      steps: [6, 7],
      objective: [
        'pair-add-0',
        'pair-add-1',
        'pair-add-2',
        'pair-add-3',
        'pair-add-4',
        'pair-add-5',
        'pair-sub-0',
        'pair-sub-1',
        'pair-sub-2',
        'pair-sub-3',
        'pair-sub-4',
        'pair-sub-5',
      ],
      manual: ['actual-add-pairs', 'actual-sub-pairs'],
      records: ['reflection', 'plan'],
      boundary:
        '加法12/6/4/3、减法18/5/3/2，各两不同卡；交换加法顺序不增一对。',
    },
    {
      page: 8,
      sourceActivity: 'pigeons',
      scope: '9+5接数、先凑9和先凑5两方法',
      lesson: 'bnu-lower-happy-farm',
      steps: [1, 2, 3],
      objective: ['sum-0', 'nine-first', 'five-first'],
      manual: ['actual-pigeons'],
      records: [],
      boundary: '两鸽群9/5不混全图动物；指定方法的四空不否定其它合理算法。',
    },
    {
      page: 8,
      sourceActivity: 'chickens',
      scope: '4+8的两种凑十',
      lesson: 'bnu-lower-happy-farm',
      steps: [4],
      objective: ['sum-1', 'four-first', 'eight-first'],
      manual: ['actual-chickens'],
      records: [],
      boundary: '分别拆8取6与拆4取2，总量12不因方法改变。',
    },
    {
      page: 9,
      sourceActivity: 'ducks',
      scope: '7+4的两种凑十',
      lesson: 'bnu-lower-happy-farm',
      steps: [4],
      objective: ['sum-2', 'seven-first', 'four-duck-first'],
      manual: ['actual-ducks'],
      records: [],
      boundary: '分别凑7与凑4，另一数剩1，总量11；原图点数独立。',
    },
    {
      page: 9,
      sourceActivity: 'bottles-birds',
      scope: '两组瓶8+5与鸟4+9圈十列式',
      lesson: 'bnu-lower-happy-farm',
      steps: [7],
      objective: ['sum-3', 'sum-4'],
      manual: ['actual-bottles', 'actual-birds'],
      records: [],
      boundary: '总量都13但瓶/只单位不同，不把两种对象合答。',
    },
    {
      page: 9,
      sourceActivity: 'stairs-exchange',
      scope: '台阶两侧八式与四交换关系',
      lesson: 'bnu-lower-happy-farm',
      steps: [5],
      objective: [
        'stairs-0',
        'stairs-1',
        'stairs-2',
        'stairs-3',
        'stairs-4',
        'stairs-5',
        'stairs-6',
        'stairs-7',
      ],
      manual: ['actual-eight-stairs'],
      records: [],
      boundary: '9+2/6/7/8与对应交换逐项算；规律不替代每式。',
    },
    {
      page: 9,
      sourceActivity: 'eight-six-jumps',
      scope: '8+6六次+1与先+2再四次+1',
      lesson: 'bnu-lower-happy-farm',
      steps: [6],
      objective: [
        'first-jump',
        'second-jump',
        'six-jumps',
        'eight-six',
        'zero-ones',
      ],
      manual: ['actual-two-jumps'],
      records: [],
      boundary: '先到10仍剩4；zero-ones是恰成十的迁移，起点不是第一跳。',
    },
    {
      page: 9,
      sourceActivity: 'open-pictures',
      scope: '人物与松鼠自定清楚分组、点数、列式解释',
      lesson: 'bnu-lower-happy-farm',
      steps: [7],
      objective: [],
      manual: ['actual-children', 'actual-squirrels'],
      records: ['reflection', 'plan'],
      boundary:
        '允许合理分组，原图数量必须实际核对，不固定性别或猜遮挡；网页不冒自动评分开放题。',
    },
    {
      page: 10,
      sourceActivity: 'own-questions',
      scope: '洗盘7/6与叠衣6/5四信息自主加法提问',
      lesson: 'bnu-lower-household-chores',
      steps: [1],
      objective: [],
      manual: ['actual-questions'],
      records: [],
      boundary: '两类对象不混算；原图人物角色不由外观推断。',
    },
    {
      page: 10,
      sourceActivity: 'plates-counter',
      scope: '7+6接数、两凑十及13个一换十',
      lesson: 'bnu-lower-household-chores',
      steps: [2, 3],
      objective: ['sum-0', 'seven-first', 'six-first', 'exchange', 'zero-ones'],
      manual: ['actual-plates', 'actual-exchange'],
      records: [],
      boundary:
        '添数量与换位分时刻；换十保持13，不另加10，散一0为另一个恰成十迁移。',
    },
    {
      page: 11,
      sourceActivity: 'clothes-methods',
      scope: '6+5接数和先凑6/5两方法',
      lesson: 'bnu-lower-household-chores',
      steps: [4],
      objective: ['sum-1', 'clothes-six', 'clothes-five'],
      manual: ['actual-clothes'],
      records: [],
      boundary: '衣服单位件；两路径同为11，不将指定路径视唯一算法。',
    },
    {
      page: 11,
      sourceActivity: 'oranges-cabbages',
      scope: '橙7+7与白菜8+5圈十和整式',
      lesson: 'bnu-lower-household-chores',
      steps: [7],
      objective: ['sum-2', 'sum-3'],
      manual: ['actual-oranges', 'actual-cabbages'],
      records: [],
      boundary: '原图实际点数与原创卡/棒迁移不同；个与棵按原题分别读。',
    },
    {
      page: 11,
      sourceActivity: 'two-plus-three',
      scope: '7起两次+3、完整7+6=13',
      lesson: 'bnu-lower-household-chores',
      steps: [5],
      objective: ['two-jumps', 'total-add', 'last-number'],
      manual: ['actual-jumps'],
      records: [],
      boundary: '两次加3总加6；中间10与最终13不能混同。',
    },
    {
      page: 11,
      sourceActivity: 'color-regions',
      scope: '28区域逐式算与结果12/11全分类',
      lesson: 'bnu-lower-household-chores',
      steps: [6],
      objective: [
        'card-1',
        'card-2',
        'card-3',
        'card-4',
        'card-5',
        'card-6',
        'card-7',
        'card-8',
        'card-9',
        'card-10',
        'card-11',
        'card-12',
        'card-13',
        'card-14',
        'card-15',
        'card-16',
        'card-17',
        'card-18',
        'card-19',
        'card-20',
        'card-21',
        'card-22',
        'card-23',
        'card-24',
        'card-25',
        'card-26',
        'card-27',
        'card-28',
        'result-twelve',
        'result-eleven',
      ],
      manual: ['actual-color'],
      records: [],
      boundary:
        '本站文字卡重排不复制区域图；12八项、11五项，其他不涂这两类，3+9不能漏。',
    },
    {
      page: 11,
      sourceActivity: 'household-extension',
      scope: '力所能及整理与真实经历/计划分别记录',
      lesson: 'bnu-lower-household-chores',
      steps: [7],
      objective: [],
      manual: ['actual-household'],
      records: ['reflection', 'plan'],
      boundary: '明确家庭实践延伸，需同意陪伴，不由网页答对确认劳动已做。',
    },
    {
      page: 12,
      sourceActivity: 'rabbits-total',
      scope: '兔7+5与两种凑十、数线+3/+2',
      lesson: 'bnu-lower-rabbit-homes',
      steps: [1, 2],
      objective: [
        'total',
        'seven-first',
        'five-first',
        'jump-total',
        'jump-last',
      ],
      manual: ['actual-rabbits', 'actual-ten'],
      records: [],
      boundary: '1/2为房屋名字，不增加兔数；原群点数与本站标记分记。',
    },
    {
      page: 12,
      sourceActivity: 'two-homes',
      scope: '六行1+11到6+6、不同有序分配',
      lesson: 'bnu-lower-rabbit-homes',
      steps: [3],
      objective: [
        'two-homes',
        'home-partner-0',
        'home-partner-1',
        'home-partner-2',
        'home-partner-3',
        'home-partner-4',
        'home-partner-5',
        'home-partner-6',
        'home-partner-7',
        'home-partner-8',
        'home-partner-9',
        'home-partner-10',
        'home-partner-11',
        'home-partner-12',
      ],
      manual: ['actual-homes'],
      records: [],
      boundary: '原六行与本站允许空屋0/12和交换扩展分开，两个屋有名字故有序。',
    },
    {
      page: 13,
      sourceActivity: 'constant-total',
      scope: '一个加1另一个减1、合计12不变',
      lesson: 'bnu-lower-rabbit-homes',
      steps: [4],
      objective: [],
      manual: ['actual-pattern'],
      records: [],
      boundary: '观察原六行全部；两数不能同增或另一数不变却称合计不变。',
    },
    {
      page: 13,
      sourceActivity: 'four-decompositions',
      scope: '8+4已给8分2/6与其余三式拆首数',
      lesson: 'bnu-lower-rabbit-homes',
      steps: [5],
      objective: [
        'method-sum-0',
        'method-sum-1',
        'method-sum-2',
        'method-sum-3',
        'source-first-0',
        'source-first-1',
        'source-first-2',
        'source-first-3',
        'eight-first',
        'method-1',
        'method-2',
        'method-3',
      ],
      manual: ['actual-methods'],
      records: [],
      boundary:
        '原示例拆首数；指定同方法各路径明确，拆第二数为另一正确迁移，不代填首数框。',
    },
    {
      page: 13,
      sourceActivity: 'three-columns',
      scope: '三列九式含给定7+6与两个7+5',
      lesson: 'bnu-lower-rabbit-homes',
      steps: [5],
      objective: [
        'column-1',
        'column-2',
        'column-3',
        'column-4',
        'column-5',
        'column-6',
        'column-7',
        'column-8',
        'column-9',
      ],
      manual: ['actual-columns'],
      records: [],
      boundary: '固定7/9/5各列条件不同，每位置保留而不合并同式。',
    },
    {
      page: 13,
      sourceActivity: 'cookie-boxes',
      scope: '6/8/9三盒与15人每人一块',
      lesson: 'bnu-lower-rabbit-homes',
      steps: [6],
      objective: [
        'boxes-ab',
        'boxes-ac',
        'boxes-bc',
        'boxes-short',
        'boxes-left',
        'boxes-exact',
      ],
      manual: ['actual-boxes'],
      records: [],
      boundary:
        '原合适开放余量；本站正好明确附加条件，AC15正好、BC17够用余2、AB14少1。',
    },
    {
      page: 13,
      sourceActivity: 'eleven-card-game',
      scope: '1～10各一张、两卡凑11的五组与同伴游戏',
      lesson: 'bnu-lower-rabbit-homes',
      steps: [7],
      objective: ['eleven-partners', 'eleven-pairs', 'zero-ones'],
      manual: ['actual-cards', 'actual-game', 'actual-explain'],
      records: ['reflection', 'plan'],
      boundary:
        '交换顺序不增组，同一张不能复制；zero-ones为另一个恰成十迁移，网页不冒真实同伴游戏。',
    },
    {
      page: 14,
      sourceActivity: 'source-cards',
      scope: '13桌面卡逐算、得数14与首数8两分类',
      lesson: 'bnu-lower-make-addition-table',
      steps: [1],
      objective: [
        'card-1',
        'card-2',
        'card-3',
        'card-4',
        'card-5',
        'card-6',
        'card-7',
        'card-8',
        'card-9',
        'card-10',
        'card-11',
        'card-12',
        'card-13',
        'result-fourteen',
        'first-eight',
      ],
      manual: ['actual-cards', 'actual-fourteen', 'actual-eight'],
      records: [],
      boundary: '原13式保留本站重编号；不存在的8+9不得添进首数8卡组。',
    },
    {
      page: 14,
      sourceActivity: 'complete-table',
      scope: '八行36位置，10给定与26算式空全填',
      lesson: 'bnu-lower-make-addition-table',
      steps: [2, 3],
      objective: [
        'blank-A',
        'blank-B',
        'blank-C',
        'blank-D',
        'blank-E',
        'blank-F',
        'blank-G',
        'blank-H',
        'blank-I',
        'blank-J',
        'blank-K',
        'blank-L',
        'blank-M',
        'blank-N',
        'blank-O',
        'blank-P',
        'blank-Q',
        'blank-R',
        'blank-S',
        'blank-T',
        'blank-U',
        'blank-V',
        'blank-W',
        'blank-X',
        'blank-Y',
        'blank-Z',
        'row-count-11',
        'row-count-12',
        'row-count-13',
        'row-count-14',
        'row-count-15',
        'row-count-16',
        'row-count-17',
        'row-count-18',
      ],
      manual: ['actual-table'],
      records: [],
      boundary:
        '加数2～9、和11～18范围完整；未占位—不是0式，填法须服从行和顺序。',
    },
    {
      page: 14,
      sourceActivity: 'horizontal-vertical',
      scope: '横行同和、竖列固定首数与实际交流',
      lesson: 'bnu-lower-make-addition-table',
      steps: [3, 4, 5, 6, 7],
      objective: ['horizontal', 'vertical', 'nine-path', 'zero-ones'],
      manual: ['actual-horizontal', 'actual-vertical', 'actual-peer'],
      records: ['reflection', 'plan'],
      boundary:
        '交换与自由凑数不同位置填空；9+9凑十、散一0为迁移，复习反排后固定右数9不抄主表。',
    },
    {
      page: 15,
      sourceActivity: 'eggs-methods',
      scope: '两窝8/7合15、拆7数线与拆8分解',
      lesson: 'bnu-lower-unit-one-harvest',
      steps: [1, 2, 3],
      objective: ['total', 'groups', 'eight-path', 'seven-path', 'jump-total'],
      manual: ['actual-story', 'actual-line', 'actual-decomposition'],
      records: [],
      boundary: '窝数2与枚数15分开；数线+2/+5和8拆5/3凑7是两条不同方法。',
    },
    {
      page: 15,
      sourceActivity: 'two-representations',
      scope: '15小棒/1捆5散与计数器1十5一及发现',
      lesson: 'bnu-lower-unit-one-harvest',
      steps: [4, 5, 6],
      objective: [
        'sticks-total',
        'bundle-count',
        'loose-count',
        'counter-value',
        'counter-material',
        'tens-bead',
        'exchange',
        'zero-ones',
      ],
      manual: ['actual-sticks', 'actual-counter', 'actual-discovery'],
      records: ['discovery'],
      boundary:
        '15根与6珠同表示15，材料件数不等表示值；捆拆和换位不改总数，0散根为独立迁移。',
    },
    {
      page: 15,
      sourceActivity: 'question-bank',
      scope: '个人问题银行与有没有最大数的讨论',
      lesson: 'bnu-lower-unit-one-harvest',
      steps: [7],
      objective: ['largest'],
      manual: ['actual-question'],
      records: ['question-bank', 'plan'],
      boundary:
        '20只是本单元范围端点；开放问题不强抄示例，未知可待核对，未来计划另记。',
    },
    {
      page: 16,
      sourceActivity: 'stairs',
      scope: '十九级九标记与原三查询两反查',
      lesson: 'bnu-lower-unit-one-practice',
      steps: [1],
      objective: [
        'stair-A',
        'stair-B',
        'stair-C',
        'stair-D',
        'stair-E',
        'stair-F',
        'stair-G',
        'stair-H',
        'stair-I',
        'reverse-10',
        'reverse-19',
      ],
      manual: ['actual-stairs'],
      records: [],
      boundary:
        '逐踏面数1～19；本站字母替代原图且保留十给定，不去实际楼梯试错。',
    },
    {
      page: 16,
      sourceActivity: 'neighbor-sums',
      scope: '八顶数形成七独立邻和、首15及六空',
      lesson: 'bnu-lower-unit-one-practice',
      steps: [2],
      objective: [
        'neighbor-1',
        'neighbor-2',
        'neighbor-3',
        'neighbor-4',
        'neighbor-5',
        'neighbor-6',
        'neighbor-7',
      ],
      manual: ['actual-neighbors'],
      records: [],
      boundary: '8+9独立，不沿用上个15累计；重复8是两个不同位置。',
    },
    {
      page: 16,
      sourceActivity: 'nine-sums',
      scope: '三列九式完整计算与规律',
      lesson: 'bnu-lower-unit-one-practice',
      steps: [3],
      objective: [
        'sum-1',
        'sum-2',
        'sum-3',
        'sum-4',
        'sum-5',
        'sum-6',
        'sum-7',
        'sum-8',
        'sum-9',
      ],
      manual: ['actual-nine'],
      records: [],
      boundary: '6+6/7/8、7+7/8+6/9+5、9+9/8/7逐式核对，规律不能替代全部。',
    },
    {
      page: 16,
      sourceActivity: 'number-line-drawing',
      scope: '两轴5～14的6+6与11～20的18−5',
      lesson: 'bnu-lower-unit-one-practice',
      steps: [4],
      objective: ['line-add', 'line-subtract'],
      manual: ['actual-add-line', 'actual-subtract-line'],
      records: [],
      boundary: '起点/方向/间隔均指定，网页只观察不自动确认原箭头已画。',
    },
    {
      page: 17,
      sourceActivity: 'animal-pictures',
      scope: '兔两群6/7与盒内给定9、外6',
      lesson: 'bnu-lower-unit-one-practice',
      steps: [5],
      objective: ['rabbits', 'bees'],
      manual: ['actual-rabbits', 'actual-bees'],
      records: [],
      boundary: '不可见给定9不当0，盒标不另加一只；两图各算且带单位。',
    },
    {
      page: 17,
      sourceActivity: 'books-sold',
      scope: '准备19余7求售出12',
      lesson: 'bnu-lower-unit-one-practice',
      steps: [6],
      objective: ['sold'],
      manual: ['actual-sale'],
      records: [],
      boundary: '总量只分售出和剩余，不补未知事件；纸面模拟不冒真实义卖。',
    },
    {
      page: 17,
      sourceActivity: 'equation-card-matching',
      scope: '两手持与十桌面十二算式逐张配卡',
      lesson: 'bnu-lower-unit-one-practice',
      steps: [7],
      objective: [
        'card-1',
        'card-2',
        'card-3',
        'card-4',
        'card-5',
        'card-6',
        'card-7',
        'card-8',
        'card-9',
        'card-10',
        'card-11',
        'card-12',
        'match-thirteen',
        'match-fifteen',
        'zero-unchecked',
      ],
      manual: ['actual-cards'],
      records: [],
      boundary:
        '9−4/7−6为减法；遮挡值卡不猜全，一张值卡可逐次复用；未核对0迁移不冒已实际核对。',
    },
    {
      page: 17,
      sourceActivity: 'open-inequalities',
      scope: '三严格不等式的多种填法与逐空解释',
      lesson: 'bnu-lower-unit-one-practice',
      steps: [8],
      objective: ['inequalities'],
      manual: ['actual-inequalities'],
      records: ['reflection', 'question', 'plan'],
      boundary:
        '原纸面无上限；网页明确填数/结果0～20且非负减法，接受全部576组合，三空可相同。',
    },
  ],
} as const;
