export const bnuLowerRecyclingAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10763.html',
  checkedAt: '2026-10-05',
  unit: 'u5',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '72～73七原活动对应；30主任务与8新复习三宽已验，后续74起、整册全年继续。',
  activities: [
    {
      page: 72,
      sourceActivity: 'read-all-conditions-and-asked-person',
      lesson: 'bnu-lower-recycling',
      steps: [1],
      objective: ['asked', 'conditions'],
      manual: ['actual-read'],
      records: [],
    },
    {
      page: 72,
      sourceActivity: 'choose-relevant-information-for-jia',
      lesson: 'bnu-lower-recycling',
      steps: [2, 7],
      objective: ['relevant', 'unused', 'direction', 'changed-ask'],
      manual: ['actual-info'],
      records: ['information-record'],
    },
    {
      page: 73,
      sourceActivity: 'sticks-one-to-one-thirteen-plus-three',
      lesson: 'bnu-lower-recycling',
      steps: [3],
      objective: ['baseline', 'one-to-one', 'rod-groups'],
      manual: ['actual-rods'],
      records: [],
    },
    {
      page: 73,
      sourceActivity: 'all-thirteen-matched-and-three-extra-circles',
      lesson: 'bnu-lower-recycling',
      steps: [4],
      objective: ['circle-groups', 'matched', 'extra', 'total'],
      manual: ['actual-circles'],
      records: [],
    },
    {
      page: 73,
      sourceActivity: 'equation-and-complete-answer',
      lesson: 'bnu-lower-recycling',
      steps: [5],
      objective: ['equation', 'unit'],
      manual: ['actual-equation'],
      records: [],
    },
    {
      page: 73,
      sourceActivity: 'check-jia-lin-difference',
      lesson: 'bnu-lower-recycling',
      steps: [6],
      objective: ['check', 'check-method'],
      manual: ['actual-check'],
      records: [],
    },
    {
      page: 73,
      sourceActivity: 'methods-and-information-reflection',
      lesson: 'bnu-lower-recycling',
      steps: [8, 9, 10],
      objective: ['site-zero'],
      manual: ['actual-discuss', 'actual-own'],
      records: ['method-record', 'difficulty-record', 'plan'],
    },
  ],
} as const;
