/** Printed pages 33–34 source activity correspondence. */
export const bnuLowerMeetingAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10761.html',
  checkedAt: '2026-10-05',
  unit: 'u3',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅印刷33～34页开会啦原活动与明示迁移；35页起仍制作中，不证明整单元、全册或全年。',
  activities: [
    {
      page: 33,
      sourceActivity: 'match',
      scope: '11人与7椅一一对应',
      lesson: 'bnu-lower-meeting',
      steps: [1],
      objective: ['people', 'chairs', 'missing', 'paired'],
      manual: ['actual-match'],
      records: [],
      boundary: '每人一把，未配到4，不把人椅合成人数。',
    },
    {
      page: 33,
      sourceActivity: 'draw',
      scope: '原两种图示与符号约定',
      lesson: 'bnu-lower-meeting',
      steps: [2],
      objective: ['diagram', 'symbols'],
      manual: ['actual-draw'],
      records: [],
      boundary: '一种符号每个对象，不按形状猜十，实画另记。',
    },
    {
      page: 33,
      sourceActivity: 'expressions',
      scope: '补缺加法与求缺减法',
      lesson: 'bnu-lower-meeting',
      steps: [3],
      objective: ['addition', 'subtraction', 'full-chairs', 'seven-role'],
      manual: ['actual-expressions'],
      records: [],
      boundary: '已有/总需/缺量与单位分别说明，括号标待补。',
    },
    {
      page: 34,
      sourceActivity: 'compare',
      scope: '原两式比较与明示相等/多余迁移',
      lesson: 'bnu-lower-meeting',
      steps: [4],
      objective: ['zero-missing', 'extra-missing', 'extra-spare', 'unknown'],
      manual: ['actual-compare'],
      records: [],
      boundary: '原比较与本站新条件分开，物多则缺0不是负数，未知不猜0。',
    },
    {
      page: 34,
      sourceActivity: 'shovels',
      scope: '原12人6把一一对应',
      lesson: 'bnu-lower-meeting',
      steps: [5],
      objective: [
        'shovel-people',
        'shovel-tools',
        'shovel-missing',
        'shovel-unit',
      ],
      manual: ['actual-shovels'],
      records: [],
      boundary: '每人一把共需12，缺6把。',
    },
    {
      page: 34,
      sourceActivity: 'apples',
      scope: '原12动物7苹果及自主问题',
      lesson: 'bnu-lower-meeting',
      steps: [6],
      objective: ['animals', 'apples', 'apple-missing', 'apple-after'],
      manual: ['actual-animals', 'actual-question'],
      records: ['own-question'],
      boundary: '每只一个缺5，补齐总12；不限制自主问题为本站示例。',
    },
    {
      page: 34,
      sourceActivity: 'calculate',
      scope: '原八式与本站两方法',
      lesson: 'bnu-lower-meeting',
      steps: [7],
      objective: [
        'calculate-0',
        'calculate-1',
        'calculate-2',
        'calculate-3',
        'calculate-4',
        'calculate-5',
        'calculate-6',
        'calculate-7',
        'parts',
        'break',
      ],
      manual: ['actual-calculate'],
      records: [],
      boundary: '全部八式覆盖，拆原数与拆减数路径分开，原算法开放。',
    },
    {
      page: 34,
      sourceActivity: 'tables',
      scope: '两给定与十二待填格',
      lesson: 'bnu-lower-meeting',
      steps: [8],
      objective: [
        'given',
        'table-six',
        'table-seven',
        'horizontal',
        'same-column',
      ],
      manual: ['actual-tables'],
      records: [],
      boundary: '首5和末10为给定，两行固定6/7分别算，横向与同列条件不同。',
    },
    {
      page: 34,
      sourceActivity: 'explain',
      scope: '表达与本站反思计划',
      lesson: 'bnu-lower-meeting',
      steps: [9],
      objective: [],
      manual: ['actual-explain'],
      records: ['discovery', 'difficulty', 'plan'],
      boundary: '实际解释、发现、困难与未来计划分别保存，不评分。',
    },
  ],
} as const;
