/** Source activities mapped to stable task IDs; learner activity and teacher review remain separate. */
export const bnuFinalAudit = {
  resourceId: 'keben-0061',
  source: 'https://keben.app/book/0061',
  checkedAt: '2026-10-04',
  unit: 'final',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '印刷81～86页总复习与87页附页学具；仅证明所列活动与原创课包的对应，不证明全册、下册或全年完成。',
  activities: [
    {
      page: 81,
      sourceActivity: 'number-meaning',
      scope: '数字意义举例与单位',
      lesson: 'bnu-upper-final-number-talk',
      steps: [1],
      objective: ['q1', 'unit', 'basket'],
      manual: ['actual-meaning'],
      records: ['meaning-record'],
      boundary: '根与筐等不同计数单位分开；筐内数量未知不填0。',
    },
    {
      page: 81,
      sourceActivity: 'open-drawing',
      scope: '严格多于四、少于六的自主作图',
      lesson: 'bnu-upper-final-number-talk',
      steps: [2],
      objective: ['open-drawing', 'equal', 'paper-limit'],
      manual: ['actual-draw'],
      records: [],
      boundary: '原纸面无10上限；网页明确0～10，所有合法数量均接受，实画另记。',
    },
    {
      page: 81,
      sourceActivity: 'calculations-story',
      scope: '三式全部计算后自选故事',
      lesson: 'bnu-upper-final-number-talk',
      steps: [3, 4],
      objective: ['add-zero', 'subtract', 'two-step', 'story-order'],
      manual: ['actual-calculate', 'actual-story'],
      records: ['story-record'],
      boundary: '全部三式与自编故事分别记录；中间变化不能混同最终数量。',
    },
    {
      page: 81,
      sourceActivity: 'planting-questions',
      scope: '观察植树图、自主提问解决及交流',
      lesson: 'bnu-upper-final-number-talk',
      steps: [5, 6],
      objective: ['tree-groups', 'children', 'question-scope', 'unknown-tools'],
      manual: ['actual-plant-observe', 'actual-exchange'],
      records: ['plant-question', 'reflection', 'plan'],
      boundary:
        '原画与原创四组模型分开；未核清工具数量不从树数推断，计划不当已交流。',
    },
    {
      page: 82,
      sourceActivity: 'number-rows',
      scope: '两条数列的全部六空',
      lesson: 'bnu-upper-final-number-practice',
      steps: [1, 2],
      objective: ['q1', 'ascending', 'descending'],
      manual: ['actual-number-rows'],
      records: [],
      boundary: '0是有效末项，不能当空；保持原序与每次变化。',
    },
    {
      page: 82,
      sourceActivity: 'queue',
      scope: '左队首九孩子全部标序',
      lesson: 'bnu-upper-final-number-practice',
      steps: [3],
      objective: ['queue'],
      manual: ['actual-queue'],
      records: [],
      boundary: '完整标1～9，不只做其中一个位置；原图与原创队列分别核对。',
    },
    {
      page: 82,
      sourceActivity: 'matching',
      scope: '十二式计算及六等值配对',
      lesson: 'bnu-upper-final-number-practice',
      steps: [4],
      objective: [
        'calculate-left',
        'calculate-right',
        'match-1',
        'match-2',
        'match-3',
        'match-4',
        'match-5',
        'match-6',
      ],
      manual: ['actual-matching'],
      records: [],
      boundary: '每个算式与配对均保留，不以一个例子代替全部。',
    },
    {
      page: 82,
      sourceActivity: 'open-blanks',
      scope: '四组唯一与多解填空',
      lesson: 'bnu-upper-final-number-practice',
      steps: [5],
      objective: ['greater', 'less', 'equal', 'difference'],
      manual: ['actual-open'],
      records: [],
      boundary: '严格不等式与两空共同算差；纸面未限上界不被网页范围否定。',
    },
    {
      page: 82,
      sourceActivity: 'stories',
      scope: '两群猴子合并与白菜隐藏量',
      lesson: 'bnu-upper-final-number-practice',
      steps: [6],
      objective: ['monkeys', 'monkey-equations', 'cabbage', 'basket-unit'],
      manual: ['actual-monkeys', 'actual-cabbage', 'actual-exchange'],
      records: ['reflection', 'question', 'plan'],
      boundary: '总10、篮外1与篮内未知分清；篮子不作为白菜计数。',
    },
    {
      page: 83,
      sourceActivity: 'calculations',
      scope: '四列十二式完整计算',
      lesson: 'bnu-upper-final-color-patterns',
      steps: [1],
      objective: ['q1', 'column-1', 'column-2', 'column-3', 'column-4'],
      manual: ['actual-calculations'],
      records: [],
      boundary: '同加数/同和规律不能取代每式实际计算。',
    },
    {
      page: 83,
      sourceActivity: 'chicks',
      scope: '两幅小鸡图的合并、可见与隐藏',
      lesson: 'bnu-upper-final-color-patterns',
      steps: [2, 3],
      objective: [
        'chicks-total',
        'chicks-equations',
        'chicks-add',
        'chicks-hidden',
        'chicks-hidden-equations',
        'chicks-unknown',
      ],
      manual: ['actual-chicks'],
      records: [],
      boundary: '右图沿用同一群共10且无增减的条件须明示；条件缺失不猜0。',
    },
    {
      page: 83,
      sourceActivity: 'color',
      scope: '二十九区域计算、涂色及发现',
      lesson: 'bnu-upper-final-color-patterns',
      steps: [4],
      objective: [
        'color-calculate-1',
        'color-calculate-2',
        'color-calculate-3',
        'color-calculate-4',
        'color-calculate-5',
        'color-select',
        'color-repeat',
      ],
      manual: ['actual-color'],
      records: [],
      boundary: '两个0+8是不同区域；原创区域卡不是原书涂色后图案。',
    },
    {
      page: 83,
      sourceActivity: 'dots',
      scope: '逐层六幅接画、完整计数及交流',
      lesson: 'bnu-upper-final-color-patterns',
      steps: [5, 6],
      objective: ['dots-known', 'dots-next', 'dots-row', 'dots-range'],
      manual: ['actual-draw', 'actual-count', 'actual-exchange'],
      records: ['reflection', 'question', 'plan'],
      boundary: '1/3/6/10/15/21全部保留，不截十，不提前要求公式。',
    },
    {
      page: 84,
      sourceActivity: 'life-objects',
      scope: '七生活物品完整四体配对',
      lesson: 'bnu-upper-final-solids',
      steps: [1],
      objective: [
        'q1',
        'life-1',
        'life-2',
        'life-3',
        'life-4',
        'life-5',
        'life-6',
        'life-7',
        'life-counts',
      ],
      manual: ['actual-life', 'actual-home'],
      records: [],
      boundary: '整体形状与画面中的面/颜色分开；真实家中观察是明确延伸。',
    },
    {
      page: 84,
      sourceActivity: 'stability',
      scope: '三种搭法、承托与滚动',
      lesson: 'bnu-upper-final-solids',
      steps: [2],
      objective: ['stability', 'stability-reason'],
      manual: ['actual-stability'],
      records: [],
      boundary: '图示比较不保证任意实物尺寸均稳定，实际操作另外确认。',
    },
    {
      page: 84,
      sourceActivity: 'materials',
      scope: '两作品与两组各八材料逐件配对',
      lesson: 'bnu-upper-final-solids',
      steps: [3, 4],
      objective: [
        'roof',
        'match-1',
        'match-2',
        'material-A',
        'roof-A',
        'material-B',
        'roof-B',
      ],
      manual: ['actual-materials'],
      records: [],
      boundary: '中间短柱是第三圆柱；屋顶部件单列，件数不被观察面数改变。',
    },
    {
      page: 84,
      sourceActivity: 'robot',
      scope: '机器人独立部件完整四类计数',
      lesson: 'bnu-upper-final-solids',
      steps: [5, 6],
      objective: ['robot-counts', 'robot-paint', 'robot-end'],
      manual: ['actual-robot', 'actual-build', 'actual-exchange'],
      records: ['reflection', 'question', 'plan'],
      boundary:
        '原PDF放大核清2/8/2/4；眼嘴画记与圆柱端面不增件。自主搭建为延伸。',
    },
    {
      page: 85,
      sourceActivity: 'legs',
      scope: '第一组四动物按脚数分类',
      lesson: 'bnu-upper-final-classification',
      steps: [1],
      objective: ['q1', 'legs-two', 'legs-four', 'legs-counts'],
      manual: ['actual-legs'],
      records: [],
      boundary: '动物张数与每只脚数分开，图标不作为生物脚数证据。',
    },
    {
      page: 85,
      sourceActivity: 'habitat',
      scope: '第二组四动物讨论主要生活环境',
      lesson: 'bnu-upper-final-classification',
      steps: [2],
      objective: ['sea', 'eagle-home', 'unknown'],
      manual: ['actual-habitat'],
      records: [],
      boundary: '鹰飞行位置不代表全部生活环境；海龟主要环境与临时上岸分开。',
    },
    {
      page: 85,
      sourceActivity: 'motion',
      scope: '七动物主要活动方式示例分类',
      lesson: 'bnu-upper-final-classification',
      steps: [3],
      objective: [
        'flying',
        'running',
        'swimming',
        'motion-counts',
        'exclusive',
      ],
      manual: ['actual-motion'],
      records: [],
      boundary:
        '照片姿态不冒当正在跑；首飞鸟品种未知，动物多种能力与其它合理标准开放。',
    },
    {
      page: 85,
      sourceActivity: 'objects',
      scope: '六物品按形状、颜色、大小换标准',
      lesson: 'bnu-upper-final-classification',
      steps: [4, 5, 6],
      objective: [
        'cuboids',
        'spheres',
        'cylinders',
        'shape-counts',
        'size',
        'color',
        'criterion',
        'total',
      ],
      manual: [
        'actual-shape',
        'actual-color',
        'actual-size',
        'actual-exchange',
      ],
      records: ['own', 'reflection', 'plan'],
      boundary:
        '恢复全部再重分；多色球不强归单色，大小仅同形对内示意，不冒实测。',
    },
    {
      page: 86,
      sourceActivity: 'recall',
      scope: '介绍位置、真实时间记录与珍惜时间回顾',
      lesson: 'bnu-upper-final-position-time',
      steps: [1, 5],
      objective: ['reference', 'front', 'period'],
      manual: ['actual-position', 'actual-record', 'actual-exchange'],
      records: ['evaluate-position', 'evaluate-time', 'record', 'plan'],
      boundary:
        '前后需面对方向，钟面不能推上午下午；未观察可待做，合理安排含休息和游戏。',
    },
    {
      page: 86,
      sourceActivity: 'flower',
      scope: '右星示范与上方、左边、下方三处作图',
      lesson: 'bnu-upper-final-position-time',
      steps: [1, 2],
      objective: ['flower-fill', 'flower-star'],
      manual: ['actual-flower'],
      records: [],
      boundary: '空图字母不泄填法，完成示意不自动确认纸面已画。',
    },
    {
      page: 86,
      sourceActivity: 'items',
      scope: '两排四列物件示范及全部三填空',
      lesson: 'bnu-upper-final-position-time',
      steps: [3],
      objective: ['q1', 'balloon', 'lamp', 'cup'],
      manual: ['actual-items'],
      records: [],
      boundary: '保持八物件行列参照，手机图内横滚；画面上下不当实物前后。',
    },
    {
      page: 86,
      sourceActivity: 'clocks',
      scope: '四钟面完整连线及拨针说明',
      lesson: 'bnu-upper-final-position-time',
      steps: [4],
      objective: [
        'clock-1',
        'clock-2',
        'clock-3',
        'clock-4',
        'half-between',
        'long-hands',
      ],
      manual: ['actual-clock-match', 'actual-clock-dial'],
      records: [],
      boundary:
        '12/3半/8半/10半独立辨长短针，不按原标签位置猜；实拨与纸面替代如实记。',
    },
    {
      page: 87,
      sourceActivity: 'annex',
      scope: '附页九卡颜色和形状各三、两轮分类',
      lesson: 'bnu-upper-final-position-time',
      steps: [6],
      objective: [
        'annex-circle',
        'annex-square',
        'annex-triangle',
        'annex-yellow',
        'annex-blue',
        'annex-green',
        'annex-shape-counts',
        'annex-color-counts',
      ],
      manual: ['actual-annex'],
      records: [],
      boundary:
        '附页不是正式新单元；恢复全部九卡再换标准，剪裁成人协助，不要求新购。',
    },
  ],
} as const;
