/** Printed pages 35–37 source activity correspondence. */
export const bnuLowerParachuteAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10761.html',
  checkedAt: '2026-10-05',
  unit: 'u3',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅印刷35～37页跳伞表演原活动与明示迁移；原37页角色分组人数未文字标明，保留实际核对与开放记录，不冒自动核准。38页起仍制作中，不证明整单元、全册或全年。',
  activities: [
    {
      page: 35,
      sourceActivity: 'colors',
      scope: '原三色伞全部数量',
      lesson: 'bnu-lower-parachute',
      steps: [1],
      objective: ['red', 'yellow', 'blue'],
      manual: ['actual-colors'],
      records: [],
      boundary: '原14红6黄7蓝，一个符号一伞，不按大小位置增物。',
    },
    {
      page: 35,
      sourceActivity: 'pairs',
      scope: '原两组对应与明示相等迁移',
      lesson: 'bnu-lower-parachute',
      steps: [2],
      objective: ['red-yellow', 'red-blue', 'inverse', 'zero-difference'],
      manual: ['actual-pair'],
      records: [],
      boundary: '较大减较小，同差反向多/少；本站相等差0与原图分开。',
    },
    {
      page: 36,
      sourceActivity: 'compare-objects',
      scope: '书11/8与苹果13/6',
      lesson: 'bnu-lower-parachute',
      steps: [3],
      objective: ['books', 'apples', 'book-unit'],
      manual: ['actual-comparisons'],
      records: [],
      boundary: '本/个不混，总量与差分开。',
    },
    {
      page: 36,
      sourceActivity: 'eggs',
      scope: '昨天11今天5的比较',
      lesson: 'bnu-lower-parachute',
      steps: [4],
      objective: ['eggs', 'egg-meaning'],
      manual: ['actual-eggs'],
      records: [],
      boundary: '两天各自产蛋不是拿走或鸡只数。',
    },
    {
      page: 36,
      sourceActivity: 'pattern',
      scope: '三同差9与自主新组',
      lesson: 'bnu-lower-parachute',
      steps: [5],
      objective: [
        'pattern-original',
        'pattern-condition',
        'pattern-continue',
        'free-difference',
      ],
      manual: ['actual-pattern'],
      records: ['own-formulas'],
      boundary: '两数同增1才差不变，0～20是本站范围，原自主组不限定本站续写。',
    },
    {
      page: 37,
      sourceActivity: 'peaches',
      scope: '原摘7与16比较',
      lesson: 'bnu-lower-parachute',
      steps: [6],
      objective: ['peach-person', 'peach-difference'],
      manual: ['actual-peaches'],
      records: [],
      boundary: '已摘文字量，不加入未摘树果。',
    },
    {
      page: 37,
      sourceActivity: 'shapes',
      scope: '原三类全部计数与两比较',
      lesson: 'bnu-lower-parachute',
      steps: [6],
      objective: ['shapes', 'triangle-less', 'square-more'],
      manual: ['actual-shapes'],
      records: [],
      boundary: '三角5圆14方15，旋转不变类别，不漏或重复。',
    },
    {
      page: 37,
      sourceActivity: 'mail',
      scope: '原十二式全部四箱',
      lesson: 'bnu-lower-parachute',
      steps: [7],
      objective: [
        'mail-0',
        'mail-1',
        'mail-2',
        'mail-3',
        'mail-4',
        'mail-5',
        'mail-6',
        'mail-7',
        'mail-8',
        'mail-9',
        'mail-10',
        'mail-11',
        'group-6',
        'group-7',
        'group-8',
        'group-9',
      ],
      manual: ['actual-mail'],
      records: [],
      boundary: '旁列八式加手持四式全覆盖，本站编号，同结果各卡保留。',
    },
    {
      page: 37,
      sourceActivity: 'children',
      scope: '原比较活动与明确给定新情境',
      lesson: 'bnu-lower-parachute',
      steps: [8],
      objective: [
        'labeled-difference',
        'labeled-inverse',
        'labeled-total',
        'unknown',
      ],
      manual: ['actual-children'],
      records: ['original-children'],
      boundary:
        '原插画分组未文字标明，实际核对/未知原话保存；本站明确9女8男不冒原图核准人数，也不由现实发型服装判断。',
    },
    {
      page: 37,
      sourceActivity: 'explain',
      scope: '比较说明与本站反思计划',
      lesson: 'bnu-lower-parachute',
      steps: [9],
      objective: ['difference-meaning'],
      manual: ['actual-explain'],
      records: ['discovery', 'difficulty', 'plan'],
      boundary: '差量意义独立，实际解释与发现困难未来计划分开，不评分。',
    },
  ],
} as const;
