export const bnuLowerRedFruitAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10762.html',
  checkedAt: '2026-10-05',
  unit: 'u4',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅50～51页七项原活动与明说的新条件；52页起仍制作，不证明整个第四单元、全年或最终教师审校。',
  activities: [
    {
      page: 50,
      sourceActivity: 'compare-story',
      lesson: 'bnu-lower-red-fruit',
      steps: [1],
      objective: [
        'story-counts',
        'count-up',
        'benchmark',
        'larger-fruit',
        'decorations',
      ],
      manual: ['actual-count-up', 'actual-benchmark'],
      records: [],
      boundary: '给定21/18；接数与20参照分别完整说明，不数装饰或编造新增数量。',
    },
    {
      page: 50,
      sourceActivity: 'do-and-fill',
      lesson: 'bnu-lower-red-fruit',
      steps: [2],
      objective: ['do-read', 'do-sign', 'same-representations'],
      manual: ['actual-do', 'actual-fill'],
      records: [],
      boundary: '真实做、完整填与解释分别记录，材料与计数器是同数不同表示。',
    },
    {
      page: 50,
      sourceActivity: 'write-and-compare',
      lesson: 'bnu-lower-red-fruit',
      steps: [3],
      objective: [
        'write-read',
        'write-thirties',
        'write-hundred',
        'hundred-beads',
        'ninety-nine-beads',
        'bead-comparison',
        'same-tens',
      ],
      manual: ['actual-write-thirties', 'actual-write-hundred'],
      records: [],
      boundary:
        '两组完整写数比数；百位一珠与18珠分别表示100与99，确定0不冒未知。',
    },
    {
      page: 51,
      sourceActivity: 'number-ruler',
      lesson: 'bnu-lower-red-fruit',
      steps: [4],
      objective: [
        'ruler-ticks',
        'ruler-above45',
        'ruler-below90',
        'ruler-nontick',
        'ruler-direction',
      ],
      manual: ['actual-ruler', 'actual-ruler-open'],
      records: [],
      boundary:
        '完整十四标数与两开放空；所有严格满足条件的整数合法，不限定5倍数。',
    },
    {
      page: 51,
      sourceActivity: 'practice-compare',
      lesson: 'bnu-lower-red-fruit',
      steps: [5],
      objective: [
        'practice-read',
        'practice-forty',
        'practice-seventy',
        'practice-last',
        'practice-eighty-ones',
      ],
      manual: ['actual-practice-pairs'],
      records: [],
      boundary: '三组全部覆盖，放大核定最后为89，按高位比较而非单看个位。',
    },
    {
      page: 51,
      sourceActivity: 'practice-open',
      lesson: 'bnu-lower-red-fruit',
      steps: [6],
      objective: [
        'open-above15',
        'open-above89',
        'open-below30',
        'open-below80',
        'open-equal',
        'open-original-range',
      ],
      manual: ['actual-open-four'],
      records: [],
      boundary:
        '四空各独立接受网页范围内全部合法整数，100与0合法场景保留，原题范围不冒写。',
    },
    {
      page: 51,
      sourceActivity: 'connect-all',
      lesson: 'bnu-lower-red-fruit',
      steps: [7, 8],
      objective: [
        'connect-less',
        'connect-greater',
        'equal-sixty',
        'all-card-count',
      ],
      manual: ['actual-connect', 'actual-explain'],
      records: ['own-method', 'discovery', 'difficulty', 'plan'],
      boundary:
        '全部九卡严格分类，换60不得入两边；真实连线交流与开放反思、未来计划分别记。',
    },
  ],
} as const;
