export const bnuLowerInterestingAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10763.html',
  checkedAt: '2026-10-05',
  unit: 'u5',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope: '70～71全部六原活动对应；72页起后续、整册全年与最终教师试用未核验。',
  activities: [
    {
      page: 70,
      sourceActivity: 'reversed-addends-and-repeated-result-digits',
      lesson: 'bnu-lower-interesting',
      steps: [1, 9, 10],
      objective: [
        'examples',
        'example-digits',
        'reverse-meaning',
        'leading-zero',
        'site-zero',
      ],
      manual: ['actual-examples', 'actual-own'],
      records: ['method-record', 'plan'],
    },
    {
      page: 70,
      sourceActivity: 'find-reversed-addends-sum44',
      lesson: 'bnu-lower-interesting',
      steps: [2],
      objective: ['find44', 'source44-examples', 'repeated-addend'],
      manual: ['actual-find44'],
      records: [],
    },
    {
      page: 71,
      sourceActivity: 'three-reversed-addend-equations-sum99',
      lesson: 'bnu-lower-interesting',
      steps: [3],
      objective: ['find99', 'source99-examples'],
      manual: ['actual-find99'],
      records: [],
    },
    {
      page: 71,
      sourceActivity: 'all-eight-addition-rows-and-discovery',
      lesson: 'bnu-lower-interesting',
      steps: [4, 5],
      objective: [
        'addition-all',
        'addition-increase',
        'addition-place-increase',
      ],
      manual: ['actual-addition', 'actual-addition-discussion'],
      records: ['addition-discovery'],
    },
    {
      page: 71,
      sourceActivity: 'all-eight-subtraction-rows-and-discovery',
      lesson: 'bnu-lower-interesting',
      steps: [6, 7],
      objective: [
        'subtraction-all',
        'subtraction-increase',
        'subtraction-place-increase',
      ],
      manual: ['actual-subtraction', 'actual-subtraction-discussion'],
      records: ['subtraction-discovery'],
    },
    {
      page: 71,
      sourceActivity: 'all-eight-add-eleven-blanks-and-discovery',
      lesson: 'bnu-lower-interesting',
      steps: [8],
      objective: ['eleven-all', 'eleven-places'],
      manual: ['actual-eleven', 'actual-eleven-discussion'],
      records: ['eleven-discovery'],
    },
  ],
} as const;
