/** Printed pages 38–39; source coverage is separate from final teacher review. */
export const bnuLowerCountrysideAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10761.html',
  checkedAt: '2026-10-05',
  unit: 'u3',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅38～39页全部所列活动及明示迁移，树上鸟5只、松鼠左7右2逐对象核对；40页起仍制作中，不证明整单元、全册或全年。',
  activities: [
    {
      page: 38,
      sourceActivity: 'six-groups',
      scope: '全部六组信息',
      lesson: 'bnu-lower-countryside',
      steps: [1],
      objective: ['six-groups'],
      manual: ['actual-six'],
      records: [],
      boundary: '空11树5岸6河8白羊7深羊5；翅膀尾角不增物。',
    },
    {
      page: 38,
      sourceActivity: 'bird-comparison',
      scope: '原求差与相等迁移',
      lesson: 'bnu-lower-countryside',
      steps: [2],
      objective: ['bird-comparison', 'zero-difference', 'difference-or-total'],
      manual: ['actual-birds'],
      records: [],
      boundary: '原差6，合计16不同；新相等0条件完整。',
    },
    {
      page: 38,
      sourceActivity: 'addition-meaning',
      scope: '8＋6解释及本站合鸟合羊例子',
      lesson: 'bnu-lower-countryside',
      steps: [3],
      objective: [
        'addition-result',
        'addition-meaning',
        'bird-total',
        'sheep-example',
      ],
      manual: ['actual-addition'],
      records: [],
      boundary:
        '原河中8只、岸上6只共14，本站合鸟16和合羊12是例子，非原自主题唯一。',
    },
    {
      page: 39,
      sourceActivity: 'own-countryside',
      scope: '原自主提出问题并解答',
      lesson: 'bnu-lower-countryside',
      steps: [4],
      objective: [],
      manual: ['actual-own-countryside'],
      records: ['own-countryside'],
      boundary: '保留完整条件、所求、式子、答句与单位，开放多解。',
    },
    {
      page: 39,
      sourceActivity: 'practice-counts',
      scope: '三组全部信息',
      lesson: 'bnu-lower-countryside',
      steps: [5],
      objective: ['practice-counts'],
      manual: ['actual-practice-counts'],
      records: [],
      boundary: '松鼠9鹿14鸭17各自点，左树卷尾不作额外身体。',
    },
    {
      page: 39,
      sourceActivity: 'deer-comparison',
      scope: '鹿比松鼠多多少',
      lesson: 'bnu-lower-countryside',
      steps: [5],
      objective: ['deer-difference'],
      manual: ['actual-practice-compare'],
      records: [],
      boundary: '14−9=5，不用鸭数量。',
    },
    {
      page: 39,
      sourceActivity: 'subtraction-meaning',
      scope: '17−9所求',
      lesson: 'bnu-lower-countryside',
      steps: [5],
      objective: ['duck-difference', 'subtraction-meaning'],
      manual: [],
      records: [],
      boundary: '鸭比松鼠多8，原未给游走事件。',
    },
    {
      page: 39,
      sourceActivity: 'own-practice',
      scope: '第二次自主提问和未知迁移',
      lesson: 'bnu-lower-countryside',
      steps: [6],
      objective: ['new-practice-question', 'unknown-group'],
      manual: ['actual-own-practice'],
      records: ['own-practice'],
      boundary: '本站鸭鹿差3只是例子，未知不能借原9。',
    },
    {
      page: 39,
      sourceActivity: 'hidden-pencils',
      scope: '12总3外求内与指定算法/0/未知迁移',
      lesson: 'bnu-lower-countryside',
      steps: [7, 8],
      objective: [
        'pencil-formula',
        'pencils-hidden',
        'pencil-to-ten',
        'pencil-break-ten',
        'zero-hidden',
        'unknown-total',
      ],
      manual: ['actual-pencils'],
      records: [],
      boundary: '9支，拆原数与拆减数不同；看不见不代表0。',
    },
    {
      page: 39,
      sourceActivity: 'hidden-shuttlecocks',
      scope: '11总4外求内与说明回顾',
      lesson: 'bnu-lower-countryside',
      steps: [7, 8],
      objective: ['shuttlecock-formula', 'units', 'shuttlecock-to-ten'],
      manual: ['actual-shuttlecocks', 'actual-explain'],
      records: ['discovery', 'difficulty', 'plan'],
      boundary: '7个，支与个不混；实际说明与发现困难未来计划分别保存。',
    },
  ],
} as const;
