/** All inspected activities on printed pages 58–59. */
export const bnuLowerNumberPracticeAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10762.html',
  checkedAt: '2026-10-05',
  unit: 'u4',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '第58～59页七项巩固应用全部原数量/候选/位置/空格对应，本站限定条件与开放原题分清；不证明最终教师审校或全年完成。',
  activities: [
    {
      page: 58,
      sourceActivity: 'four-material-compositions',
      lesson: 'bnu-lower-number-practice',
      steps: [1, 2, 3, 4],
      objective: [
        'objects',
        'sticks',
        'counter',
        'cubes-raw',
        'cubes-regrouped',
        'cubes-loose',
      ],
      manual: [
        'actual-objects',
        'actual-sticks',
        'actual-counter',
        'actual-cubes',
        'actual-regroup',
      ],
      records: ['own-method'],
    },
    {
      page: 58,
      sourceActivity: 'counter-write-game',
      lesson: 'bnu-lower-number-practice',
      steps: [3],
      objective: ['game-digits', 'game-value', 'game-beads'],
      manual: ['actual-game-first', 'actual-game-switch'],
      records: [],
    },
    {
      page: 58,
      sourceActivity: 'peach-candidates',
      lesson: 'bnu-lower-number-practice',
      steps: [5],
      objective: ['peach-reference', 'peach-selected', 'peach-less'],
      manual: ['actual-peach'],
      records: [],
    },
    {
      page: 59,
      sourceActivity: 'book-two-clues',
      lesson: 'bnu-lower-number-practice',
      steps: [6],
      objective: [
        'book-selected',
        'book-only-greater',
        'book-only-less',
        'book-incomplete',
      ],
      manual: ['actual-books'],
      records: [],
    },
    {
      page: 59,
      sourceActivity: 'four-complete-trains',
      lesson: 'bnu-lower-number-practice',
      steps: [7, 8, 9, 10],
      objective: [
        'five-up',
        'two-up',
        'ten-up',
        'five-down',
        'descending-step',
      ],
      manual: [
        'actual-train-five',
        'actual-train-two',
        'actual-train-ten',
        'actual-train-down',
      ],
      records: [],
    },
    {
      page: 59,
      sourceActivity: 'four-beads-all-five',
      lesson: 'bnu-lower-number-practice',
      steps: [11, 12],
      objective: [
        'beads-remaining',
        'beads-all',
        'beads-digits',
        'beads-zero',
        'beads-count',
      ],
      manual: ['actual-four-beads'],
      records: ['discovery'],
    },
    {
      page: 59,
      sourceActivity: 'three-cards-all-six',
      lesson: 'bnu-lower-number-practice',
      steps: [13, 14],
      objective: ['cards-six', 'cards-count', 'cards-duplicate'],
      manual: ['actual-six-cards', 'actual-explain'],
      records: ['difficulty', 'plan'],
    },
  ],
} as const;
