export const bnuLowerCountBeansAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10762.html',
  checkedAt: '2026-10-05',
  unit: 'u4',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅48～49页数豆子七项原活动及明示迁移；第50页起仍制作，不证明完整第四单元、全册、全年或最终教师审校。',
  activities: [
    {
      page: 48,
      sourceActivity: 'estimate-grab',
      lesson: 'bnu-lower-count-beans',
      steps: [1],
      objective: [
        'estimate-cases',
        'estimate-order',
        'estimate-personal',
        'estimate-direction',
        'estimate-close',
      ],
      manual: ['actual-estimate', 'actual-count', 'actual-repeat'],
      records: ['own-first-record', 'own-repeat-record'],
      boundary:
        '原估50/实28与估20/实22不是自己结果；先估后数、不倒填、无普遍误差阈值。',
    },
    {
      page: 48,
      sourceActivity: 'counter-and-write',
      lesson: 'bnu-lower-count-beans',
      steps: [2],
      objective: [
        'read-pair',
        'twenty-eight-parts',
        'twenty-eight-beads',
        'two-twos',
        'beads-and-value',
      ],
      manual: ['actual-counter-twenty-eight', 'actual-counter-twenty-two'],
      records: ['own-place-record'],
      boundary: '28图10珠表示28；22两个2表示20与2，珠数、数位与表示值分开。',
    },
    {
      page: 48,
      sourceActivity: 'recognize-hundred',
      lesson: 'bnu-lower-count-beans',
      steps: [3],
      objective: [
        'near-hundred',
        'hundred-parts',
        'hundred-beads',
        'hundred-value',
        'zero-tens',
        'unknown-counter',
        'read-hundred',
      ],
      manual: [
        'actual-ninety-seven',
        'actual-ninety-eight',
        'actual-ninety-nine',
        'actual-hundred',
      ],
      records: [],
      boundary:
        '四数实际分别拨读写，百位一珠不是一件；确定0与未给条件不同，旧计数图契约保持。',
    },
    {
      page: 49,
      sourceActivity: 'think-try',
      lesson: 'bnu-lower-count-beans',
      steps: [4],
      objective: [
        'forty-two-parts',
        'make-thirty-four',
        'same-forty-two',
        'changed-places',
      ],
      manual: ['actual-forty-two', 'actual-thirty-four'],
      records: [],
      boundary:
        '42两种表示不相加84，原34空框待做，本站补画明确原创，交换数位不同于换表示。',
    },
    {
      page: 49,
      sourceActivity: 'practice-twenty-six',
      lesson: 'bnu-lower-count-beans',
      steps: [5],
      objective: ['twenty-six-parts', 'two-bundles', 'twenty-six-beads'],
      manual: ['actual-twenty-six'],
      records: [],
      boundary: '原左两捆不冒已画六单根，完整摆拨画写另做；8珠与26表示值分开。',
    },
    {
      page: 49,
      sourceActivity: 'read-mark-draw-write',
      lesson: 'bnu-lower-count-beans',
      steps: [6],
      objective: [
        'life-read-values',
        'life-twenty-seven',
        'life-ninety-nine',
        'mission-unit',
        'historical-example',
      ],
      manual: ['actual-life-twenty-seven', 'actual-life-ninety-nine'],
      records: [],
      boundary:
        '原27次与99道弯读标画写分别覆盖，次数非飞船数量、历史信息不冒当前总次数。',
    },
    {
      page: 49,
      sourceActivity: 'find-hundred',
      lesson: 'bnu-lower-count-beans',
      steps: [7, 8],
      objective: [
        'page-hundred',
        'door-hundred',
        'label-hundred',
        'same-hundred',
        'unknown-pages',
      ],
      manual: ['actual-find-hundred', 'actual-explain'],
      records: ['own-life-record', 'discovery', 'difficulty', 'plan'],
      boundary:
        '页码/门牌/标示数量不同，未知总页和当前剩余不猜0，个人例开放、未来计划另记。',
    },
  ],
} as const;
