/** Source activity correspondence for printed pages 29–30. */
export const bnuLowerHideAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10761.html',
  checkedAt: '2026-10-05',
  unit: 'u3',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅印刷29～30页捉迷藏的活动与明示附加过程，31页起仍待制作，不证明完整单元、全册或全年。',
  activities: [
    {
      page: 29,
      sourceActivity: 'ranges',
      scope: '总人数与参与范围',
      lesson: 'bnu-lower-hide-and-seek',
      steps: [1],
      objective: ['total', 'hiders', 'unhidden', 'hidden', 'seeker', 'scope'],
      manual: ['actual-info'],
      records: [],
      boundary: '总14与躲藏13不同，寻找者不算已藏。',
    },
    {
      page: 29,
      sourceActivity: 'exchange',
      scope: '计数器表示13并退位',
      lesson: 'bnu-lower-hide-and-seek',
      steps: [2],
      objective: ['initial-counter', 'exchange'],
      manual: ['actual-exchange'],
      records: [],
      boundary:
        '表示区颗数4与总值13分清，换十总值不变，未整理13个一不是规范个位数字。',
    },
    {
      page: 29,
      sourceActivity: 'break-ten',
      scope: '破十减过程',
      lesson: 'bnu-lower-hide-and-seek',
      steps: [3],
      objective: ['break-ten', 'final-counter'],
      manual: ['actual-break'],
      records: [],
      boundary: '原数13拆10与3，已拨去标记不计剩余。',
    },
    {
      page: 29,
      sourceActivity: 'subtract-parts',
      scope: '先减到10后继续减',
      lesson: 'bnu-lower-hide-and-seek',
      steps: [4],
      objective: ['parts', 'ten-marks', 'ten-value'],
      manual: ['actual-parts'],
      records: [],
      boundary: '减数8拆3与5，到10只有1个十标记，再换一继续减。',
    },
    {
      page: 30,
      sourceActivity: 'methods',
      scope: '17减9与11减6多方法和原数线',
      lesson: 'bnu-lower-hide-and-seek',
      steps: [5],
      objective: ['method-17-9', 'method-11-6', 'line-parts', 'think-add'],
      manual: ['actual-methods', 'actual-line'],
      records: [],
      boundary: '先17到10减7再减2，图中左侧减2不是第一步。',
    },
    {
      page: 30,
      sourceActivity: 'practice-one',
      scope: '原练一计数器两式',
      lesson: 'bnu-lower-hide-and-seek',
      steps: [6],
      objective: ['practice-12-6', 'practice-16-9'],
      manual: ['actual-practice'],
      records: [],
      boundary: '全部两式真实拨画独立，网页不自动确认。',
    },
    {
      page: 30,
      sourceActivity: 'practice-two',
      scope: '原两图加减关系',
      lesson: 'bnu-lower-hide-and-seek',
      steps: [7],
      objective: [
        'bugs-total',
        'bugs-remove-left',
        'bugs-remove-right',
        'chicks-total',
        'chicks-remove-left',
        'chicks-remove-right',
      ],
      manual: ['actual-pictures'],
      records: [],
      boundary:
        '虫7/4鸡6/7逐项核对；本站指定去哪部分，原开放减法允许另一合理式。',
    },
    {
      page: 30,
      sourceActivity: 'practice-three',
      scope: '八卡摘苹果',
      lesson: 'bnu-lower-hide-and-seek',
      steps: [8],
      objective: [
        'apple-0',
        'apple-1',
        'apple-2',
        'apple-3',
        'apple-4',
        'apple-5',
        'apple-6',
        'apple-7',
      ],
      manual: ['actual-apples'],
      records: [],
      boundary: '八张全部计算，不遗漏或把卡数当结果。',
    },
    {
      page: 30,
      sourceActivity: 'explain',
      scope: '说方法与本站反思计划',
      lesson: 'bnu-lower-hide-and-seek',
      steps: [9],
      objective: [],
      manual: ['actual-explain'],
      records: ['discovery', 'difficulty', 'plan'],
      boundary: '实际说明、两份反思与计划独立，correct:null。',
    },
  ],
} as const;
