export const bnuLowerRabbitGuestsAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10763.html',
  checkedAt: '2026-10-05',
  unit: 'u5',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '印刷62～63六项原活动、三种加减方法与全部术语/两小棒/两数线/开放提问完整对应；本站小棒时刻明确与原示意分清，不证明其后64页起、整册或全年完成。',
  activities: [
    {
      page: 62,
      sourceActivity: 'fruit-addition-three-methods',
      lesson: 'bnu-lower-rabbit-guests',
      steps: [1, 2],
      objective: [
        'plate-groups',
        'add-values',
        'add-forward',
        'add-tens',
        'add-related',
        'add-beads',
      ],
      manual: ['actual-add-count', 'actual-add-tens', 'actual-add-related'],
      records: [],
    },
    {
      page: 62,
      sourceActivity: 'taken-not-left',
      lesson: 'bnu-lower-rabbit-guests',
      steps: [3, 4],
      objective: [
        'sub-values',
        'sub-backward',
        'sub-tens',
        'sub-related',
        'sub-target',
      ],
      manual: ['actual-sub-count', 'actual-sub-tens', 'actual-sub-related'],
      records: [],
    },
    {
      page: 63,
      sourceActivity: 'name-each-operation-position',
      lesson: 'bnu-lower-rabbit-guests',
      steps: [5],
      objective: [
        'add-name-20',
        'add-name-30',
        'sum-name',
        'minuend-name',
        'subtrahend-name',
        'difference-name',
      ],
      manual: ['actual-names'],
      records: [],
    },
    {
      page: 63,
      sourceActivity: 'two-stick-actions-and-units',
      lesson: 'bnu-lower-rabbit-guests',
      steps: [6, 10],
      objective: [
        'stick-add-bundles',
        'stick-add',
        'stick-sub-bundles',
        'stick-sub',
        'stick-after',
        'stick-unit',
        'site-zero',
      ],
      manual: ['actual-stick-add', 'actual-stick-sub'],
      records: [],
    },
    {
      page: 63,
      sourceActivity: 'both-arrow-lines',
      lesson: 'bnu-lower-rabbit-guests',
      steps: [7, 8],
      objective: ['line-add', 'line-sub', 'line-directions'],
      manual: ['actual-line-add', 'actual-line-sub'],
      records: [],
    },
    {
      page: 63,
      sourceActivity: 'own-peach-question-and-answer',
      lesson: 'bnu-lower-rabbit-guests',
      steps: [9, 10],
      objective: [
        'peach-values',
        'peach-pair-totals',
        'peach-pair-differences',
        'peach-most',
      ],
      manual: ['actual-own-question', 'actual-explain-question'],
      records: ['own-question-record', 'method-record', 'plan'],
    },
  ],
} as const;
