export const bnuLowerUnitSixAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10764.html',
  checkedAt: '2026-10-06',
  unit: 'u6',
  status: 'partial-original-teaching',
  finalTeacherReview: 'not-verified',
  scope:
    '76～77六原活动、43主任务和8换条件复习三宽已验；78～79七原活动、39主任务和6换条件复习三宽已验；80～82九原活动已接三课95主任务/19复习，最终生产三宽程序验收通过；83～86后续仍制作，保留单元待制作入口。',
  activities: [
    {
      page: 76,
      sourceActivity: 'predict-contact-footprints',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [1],
      objective: ['face', 'unknown-footprint'],
      manual: ['actual-footprint'],
      records: [],
    },
    {
      page: 76,
      sourceActivity: 'trace-faces-and-name-four-shapes',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [2],
      objective: ['face'],
      manual: ['actual-four-traces'],
      records: [],
    },
    {
      page: 77,
      sourceActivity: 'match-all-eleven-and-rotate-square',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [3, 4, 5],
      objective: [
        'row-1',
        'row-2',
        'row-3',
        'row-4',
        'row-5',
        'row-6',
        'row-7',
        'row-8',
        'row-9',
        'row-10',
        'row-11',
        'row-count-rectangle',
        'row-count-square',
        'row-count-circle',
        'row-count-triangle',
        'rotation-category',
        'rotation-count',
      ],
      manual: ['actual-eleven', 'actual-turn'],
      records: [],
    },
    {
      page: 77,
      sourceActivity: 'nearby-object-predict-before-tracing',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [6],
      objective: ['prediction-order'],
      manual: ['actual-predict', 'actual-trace-check'],
      records: ['prediction-record'],
    },
    {
      page: 77,
      sourceActivity: 'color-boat-and-rocket-by-four-shape-legend',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [7, 8],
      objective: [
        'color-triangle',
        'color-circle',
        'color-rectangle',
        'color-square',
        'open-lines',
      ],
      manual: ['actual-boat', 'actual-rocket'],
      records: [],
    },
    {
      page: 77,
      sourceActivity: 'count-train-four-categories',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [9, 10],
      objective: [
        'train-square',
        'train-triangle',
        'train-rectangle',
        'train-circle',
        'open-lines',
        'site-zero',
      ],
      manual: ['actual-train', 'actual-share'],
      records: ['reflection', 'plan'],
    },
    {
      page: 78,
      sourceActivity: 'square-two-equal-halves-cut-and-compare',
      lesson: 'bnu-lower-fold-one',
      steps: [1, 2],
      objective: ['halves-0', 'halves-1'],
      manual: ['actual-halves-square-mid', 'actual-halves-square-diagonal'],
      records: [],
    },
    {
      page: 78,
      sourceActivity: 'rectangle-triangle-circle-halves-cut-and-compare',
      lesson: 'bnu-lower-fold-one',
      steps: [3, 4, 5],
      objective: ['halves-2', 'halves-3', 'circle-half', 'diagonal-compare'],
      manual: [
        'actual-halves-rectangle',
        'actual-halves-triangle',
        'actual-halves-circle',
      ],
      records: ['reflection'],
    },
    {
      page: 78,
      sourceActivity: 'copy-all-four-cut-piece-patterns',
      lesson: 'bnu-lower-fold-one',
      steps: [6, 7, 8, 9],
      objective: [
        'copy-count-0',
        'copy-count-1',
        'copy-count-2',
        'copy-count-3',
      ],
      manual: [
        'actual-copy-1',
        'actual-copy-2',
        'actual-copy-3',
        'actual-copy-4',
      ],
      records: [],
    },
    {
      page: 79,
      sourceActivity: 'cooperate-create-color-and-describe',
      lesson: 'bnu-lower-fold-one',
      steps: [10, 11],
      objective: [],
      manual: ['actual-cooperate', 'actual-color', 'actual-describe'],
      records: ['cooperation-record'],
    },
    {
      page: 79,
      sourceActivity: 'fold-airplane-seven-panel-arrow-order',
      lesson: 'bnu-lower-fold-one',
      steps: [12],
      objective: ['airplane-order'],
      manual: ['actual-airplane'],
      records: [],
    },
    {
      page: 79,
      sourceActivity: 'fold-rectangle-into-square-without-mandatory-cut',
      lesson: 'bnu-lower-fold-one',
      steps: [13],
      objective: ['fold-not-cut'],
      manual: ['actual-square-fold'],
      records: [],
    },
    {
      page: 79,
      sourceActivity: 'square-four-equal-triangles-open-recomposition',
      lesson: 'bnu-lower-fold-one',
      steps: [14, 15, 16],
      objective: [
        'four-count',
        'zero-square',
        'whole-triangle',
        'whole-trapezoid',
        'open',
        'cutlines',
      ],
      manual: [
        'actual-four-cut',
        'actual-four-triangle',
        'actual-four-trapezoid',
        'actual-four-new',
      ],
      records: ['plan'],
    },
    {
      page: 80,
      sourceActivity: 'recognize-scene-and-fill-four-numbered-tangram-blanks',
      lesson: 'bnu-lower-tangram-recognize',
      steps: [1, 2, 3, 4, 5, 6, 7],
      objective: [
        'piece-1',
        'piece-2',
        'piece-3',
        'piece-4',
        'piece-5',
        'piece-6',
        'piece-7',
        'blank-kinds',
        'blank-triangles',
        'blank-large-pair',
        'blank-small-pair',
      ],
      manual: [
        'actual-source-scene',
        'actual-large-pair',
        'actual-small-pair',
        'actual-four-blanks',
      ],
      records: ['compare-record'],
    },
    {
      page: 80,
      sourceActivity: 'trace-and-describe-three-different-piece-shapes',
      lesson: 'bnu-lower-tangram-recognize',
      steps: [8, 9],
      objective: ['different-shapes', 'turn-square', 'same-category'],
      manual: [
        'actual-trace-square',
        'actual-trace-parallelogram',
        'actual-trace-triangle',
        'actual-say-three',
      ],
      records: ['trace-record', 'reflection', 'plan'],
    },
    {
      page: 81,
      sourceActivity: 'choose-and-assemble-a-favourite-poetry-scene-pattern',
      lesson: 'bnu-lower-tangram-patterns',
      steps: [1, 2, 3],
      objective: ['head-range', 'goose-categories', 'fish-pieces'],
      manual: ['actual-favourite'],
      records: ['favourite-record'],
    },
    {
      page: 81,
      sourceActivity: 'assemble-all-six-open-naming-examples',
      lesson: 'bnu-lower-tangram-patterns',
      steps: [4, 5, 6, 7, 8, 9],
      objective: [
        'open-name',
        'all-seven',
        'six-independent',
        'shape-preserved',
      ],
      manual: [
        'actual-frame-1',
        'actual-frame-2',
        'actual-frame-3',
        'actual-frame-4',
        'actual-frame-5',
        'actual-frame-6',
      ],
      records: [
        'frame-record-1',
        'frame-record-2',
        'frame-record-3',
        'frame-record-4',
        'frame-record-5',
        'frame-record-6',
      ],
    },
    {
      page: 81,
      sourceActivity: 'cooperate-invent-story-and-compose-pattern',
      lesson: 'bnu-lower-tangram-patterns',
      steps: [10, 11, 12],
      objective: ['story-choice', 'cooperation-proof'],
      manual: [
        'actual-story-invent',
        'actual-story-cooperate',
        'actual-story-assemble',
        'actual-story-tell',
      ],
      records: ['story-record', 'reflection', 'plan'],
    },
    {
      page: 82,
      sourceActivity: 'compose-two-larger-triangles',
      lesson: 'bnu-lower-tangram-practice',
      steps: [1, 2, 3],
      objective: [
        'first-pieces',
        'first-outline',
        'second-pieces',
        'second-outline',
        'relative-larger',
        'all-five',
        'internal-seam',
      ],
      manual: [
        'actual-material',
        'actual-first-triangle',
        'actual-second-triangle',
        'actual-check-two',
      ],
      records: ['triangles-record'],
    },
    {
      page: 82,
      sourceActivity: 'describe-three-people-stories-and-piece-shapes',
      lesson: 'bnu-lower-tangram-practice',
      steps: [4, 5],
      objective: ['football', 'story-open', 'single-cooperation'],
      manual: [
        'actual-person-1',
        'actual-person-2',
        'actual-person-3',
        'actual-people-exchange',
      ],
      records: ['person-record-1', 'person-record-2', 'person-record-3'],
    },
    {
      page: 82,
      sourceActivity: 'compose-and-tell-three-waiting-for-hare-patterns',
      lesson: 'bnu-lower-tangram-practice',
      steps: [6, 7],
      objective: [],
      manual: [
        'actual-hare-1',
        'actual-hare-2',
        'actual-hare-3',
        'actual-hare-tell',
      ],
      records: ['hare-record'],
    },
    {
      page: 82,
      sourceActivity: 'create-a-favourite-pattern-and-show-classmates',
      lesson: 'bnu-lower-tangram-practice',
      steps: [8, 9],
      objective: ['creation-choice', 'show-separate'],
      manual: ['actual-create', 'actual-show'],
      records: ['creation-record', 'reflection', 'plan'],
    },
  ],
  pendingPrintedPages: [83, 84, 85, 86],
} as const;
