export const bnuLowerCountHundredAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10762.html',
  checkedAt: '2026-10-05',
  unit: 'u4',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅46～47页数一数七项原活动及明示迁移；第48页起仍制作，不证明完整第四单元、全册、全年或最终教师审校。',
  activities: [
    {
      page: 46,
      sourceActivity: 'count-eggs',
      lesson: 'bnu-lower-count-hundred',
      steps: [1],
      objective: ['eggs-parts', 'eggs-right', 'empty-tray'],
      manual: ['actual-eggs', 'actual-egg-sticks'],
      records: [],
      boundary:
        '九完整盒、九桌上蛋与一手持蛋，共100；右十盒仍100，空盒不计蛋，先后图不相加。',
    },
    {
      page: 46,
      sourceActivity: 'make-ten',
      lesson: 'bnu-lower-count-hundred',
      steps: [2],
      objective: ['sticks-parts', 'make-ten', 'bundle-keeps', 'source-total'],
      manual: ['actual-ten'],
      records: [],
      boundary:
        '原9捆10根为100而非99；拆百与拆十只改分组，网页操作不自动确认实物。',
    },
    {
      page: 46,
      sourceActivity: 'make-hundred',
      lesson: 'bnu-lower-count-hundred',
      steps: [3],
      objective: [
        'hundred-parts',
        'after-ninety-nine',
        'zero-ones',
        'bundle-unit',
      ],
      manual: ['actual-hundred'],
      records: [],
      boundary:
        '十个十为百，根与捆不同；99添1是另一相邻数说明，确认0不当未填。',
    },
    {
      page: 47,
      sourceActivity: 'from-seventy-four',
      lesson: 'bnu-lower-count-hundred',
      steps: [4],
      objective: [
        'seventy-four-parts',
        'count-first',
        'count-middle',
        'count-last',
        'tens-path',
        'no-overshoot',
      ],
      manual: ['actual-seventy-four-one', 'actual-seventy-four-ten'],
      records: ['own-count-method'],
      boundary: '三段75～100全部覆盖，原方法开放，本站先十后逐一不能跳104。',
    },
    {
      page: 47,
      sourceActivity: 'continue-speaking',
      lesson: 'bnu-lower-count-hundred',
      steps: [5],
      objective: ['down-sequence', 'up-sequence', 'directions'],
      manual: ['actual-down', 'actual-up'],
      records: ['own-sequence'],
      boundary: '原续说无指定终点，本站0～100明示，其他合理续说另记。',
    },
    {
      page: 47,
      sourceActivity: 'practice-count-hundred',
      lesson: 'bnu-lower-count-hundred',
      steps: [6],
      objective: [
        'practice-sticks',
        'practice-blocks',
        'from-sixty-seven',
        'from-eighty-eight',
      ],
      manual: [
        'actual-sixty-seven',
        'actual-eighty-eight',
        'actual-material-exchange',
      ],
      records: [],
      boundary: '67与88分别完整到100并交流，不合并155，不把起数当完成。',
    },
    {
      page: 47,
      sourceActivity: 'weather-days',
      lesson: 'bnu-lower-count-hundred',
      steps: [7, 8, 9],
      objective: [
        'weather-sunny-rows',
        'weather-cloudy-rows',
        'weather-total',
        'whole-icon',
        'month',
        'unknown-weather',
        'zero-no-cloud',
        'keeps-quantity',
      ],
      manual: ['actual-weather', 'actual-weather-recheck', 'actual-explain'],
      records: [
        'own-weather-method',
        'actual-work-record',
        'discovery',
        'difficulty',
        'plan',
      ],
      boundary:
        '七行十格两类各35，按整格分、不重复太阳，不当自然月或未来天气；总结换捆数量不变、已做与未来计划分开。',
    },
  ],
} as const;
