export const bnuLowerUnitSixAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10764.html',
  checkedAt: '2026-10-05',
  unit: 'u6',
  status: 'partial-original-teaching',
  finalTeacherReview: 'not-verified',
  scope:
    '76～77六原活动、43主任务和8换条件复习三宽已验；78～79七原活动、39主任务和6换条件复习三宽已验；80～86后续仍制作，保留单元待制作入口。',
  activities: [
    {
      page: 76,
      sourceActivity: 'predict-contact-footprints',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [1],
      objective: ['face', 'unknown-footprint'],
      manual: ['actual-footprint'],
      records: [],
    },
    {
      page: 76,
      sourceActivity: 'trace-faces-and-name-four-shapes',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [2],
      objective: ['face'],
      manual: ['actual-four-traces'],
      records: [],
    },
    {
      page: 77,
      sourceActivity: 'match-all-eleven-and-rotate-square',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [3, 4, 5],
      objective: [
        'row-1',
        'row-2',
        'row-3',
        'row-4',
        'row-5',
        'row-6',
        'row-7',
        'row-8',
        'row-9',
        'row-10',
        'row-11',
        'row-count-rectangle',
        'row-count-square',
        'row-count-circle',
        'row-count-triangle',
        'rotation-category',
        'rotation-count',
      ],
      manual: ['actual-eleven', 'actual-turn'],
      records: [],
    },
    {
      page: 77,
      sourceActivity: 'nearby-object-predict-before-tracing',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [6],
      objective: ['prediction-order'],
      manual: ['actual-predict', 'actual-trace-check'],
      records: ['prediction-record'],
    },
    {
      page: 77,
      sourceActivity: 'color-boat-and-rocket-by-four-shape-legend',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [7, 8],
      objective: [
        'color-triangle',
        'color-circle',
        'color-rectangle',
        'color-square',
        'open-lines',
      ],
      manual: ['actual-boat', 'actual-rocket'],
      records: [],
    },
    {
      page: 77,
      sourceActivity: 'count-train-four-categories',
      lesson: 'bnu-lower-recognize-shapes',
      steps: [9, 10],
      objective: [
        'train-square',
        'train-triangle',
        'train-rectangle',
        'train-circle',
        'open-lines',
        'site-zero',
      ],
      manual: ['actual-train', 'actual-share'],
      records: ['reflection', 'plan'],
    },
    {
      page: 78,
      sourceActivity: 'square-two-equal-halves-cut-and-compare',
      lesson: 'bnu-lower-fold-one',
      steps: [1, 2],
      objective: ['halves-0', 'halves-1'],
      manual: ['actual-halves-square-mid', 'actual-halves-square-diagonal'],
      records: [],
    },
    {
      page: 78,
      sourceActivity: 'rectangle-triangle-circle-halves-cut-and-compare',
      lesson: 'bnu-lower-fold-one',
      steps: [3, 4, 5],
      objective: ['halves-2', 'halves-3', 'circle-half', 'diagonal-compare'],
      manual: [
        'actual-halves-rectangle',
        'actual-halves-triangle',
        'actual-halves-circle',
      ],
      records: ['reflection'],
    },
    {
      page: 78,
      sourceActivity: 'copy-all-four-cut-piece-patterns',
      lesson: 'bnu-lower-fold-one',
      steps: [6, 7, 8, 9],
      objective: [
        'copy-count-0',
        'copy-count-1',
        'copy-count-2',
        'copy-count-3',
      ],
      manual: [
        'actual-copy-1',
        'actual-copy-2',
        'actual-copy-3',
        'actual-copy-4',
      ],
      records: [],
    },
    {
      page: 79,
      sourceActivity: 'cooperate-create-color-and-describe',
      lesson: 'bnu-lower-fold-one',
      steps: [10, 11],
      objective: [],
      manual: ['actual-cooperate', 'actual-color', 'actual-describe'],
      records: ['cooperation-record'],
    },
    {
      page: 79,
      sourceActivity: 'fold-airplane-seven-panel-arrow-order',
      lesson: 'bnu-lower-fold-one',
      steps: [12],
      objective: ['airplane-order'],
      manual: ['actual-airplane'],
      records: [],
    },
    {
      page: 79,
      sourceActivity: 'fold-rectangle-into-square-without-mandatory-cut',
      lesson: 'bnu-lower-fold-one',
      steps: [13],
      objective: ['fold-not-cut'],
      manual: ['actual-square-fold'],
      records: [],
    },
    {
      page: 79,
      sourceActivity: 'square-four-equal-triangles-open-recomposition',
      lesson: 'bnu-lower-fold-one',
      steps: [14, 15, 16],
      objective: [
        'four-count',
        'zero-square',
        'whole-triangle',
        'whole-trapezoid',
        'open',
        'cutlines',
      ],
      manual: [
        'actual-four-cut',
        'actual-four-triangle',
        'actual-four-trapezoid',
        'actual-four-new',
      ],
      records: ['plan'],
    },
  ],
  pendingPrintedPages: [80, 81, 82, 83, 84, 85, 86],
} as const;
