export const bnuLowerPineconesAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10763.html',
  checkedAt: '2026-10-05',
  unit: 'u5',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '印刷64～65全部八项原活动、两方法/两解释/四摆棒/两数线/八式/两应用完整对应；不证明其后66页起、整册或全年完成。',
  activities: [
    {
      page: 64,
      sourceActivity: 'mother-child-addition-three-methods',
      lesson: 'bnu-lower-pinecones',
      steps: [1, 2],
      objective: [
        'picked',
        'add-values',
        'add-count',
        'add-ones',
        'add-tens',
        'add-related',
      ],
      manual: ['actual-add-count', 'actual-add-sticks', 'actual-add-related'],
      records: [],
    },
    {
      page: 64,
      sourceActivity: 'mother-father-comparison-three-methods',
      lesson: 'bnu-lower-pinecones',
      steps: [3],
      objective: [
        'sub-values',
        'sub-count',
        'sub-tens',
        'sub-ones',
        'sub-related',
        'compare-meaning',
      ],
      manual: ['actual-sub-count', 'actual-sub-sticks', 'actual-sub-related'],
      records: [],
    },
    {
      page: 65,
      sourceActivity: 'interpret-two-equations',
      lesson: 'bnu-lower-pinecones',
      steps: [4, 10],
      objective: ['interpret-sub', 'interpret-add', 'site-zero'],
      manual: ['actual-interpret-sub', 'actual-interpret-add', 'actual-own'],
      records: ['method-record', 'own-record', 'plan'],
    },
    {
      page: 65,
      sourceActivity: 'four-stick-calculations',
      lesson: 'bnu-lower-pinecones',
      steps: [5],
      objective: ['stick-32', 'stick-75', 'stick-78', 'stick-68'],
      manual: [
        'actual-stick-32',
        'actual-stick-75',
        'actual-stick-78',
        'actual-stick-68',
      ],
      records: [],
    },
    {
      page: 65,
      sourceActivity: 'both-arrow-lines',
      lesson: 'bnu-lower-pinecones',
      steps: [6, 7],
      objective: ['line-add', 'line-sub', 'line-directions'],
      manual: ['actual-line-add', 'actual-line-sub'],
      records: [],
    },
    {
      page: 65,
      sourceActivity: 'all-eight-calculations',
      lesson: 'bnu-lower-pinecones',
      steps: [8],
      objective: ['eight-top', 'eight-bottom'],
      manual: ['actual-eight'],
      records: [],
    },
    {
      page: 65,
      sourceActivity: 'swans-arrival-total',
      lesson: 'bnu-lower-pinecones',
      steps: [9],
      objective: ['swans', 'swans-meaning'],
      manual: ['actual-swans'],
      records: [],
    },
    {
      page: 65,
      sourceActivity: 'dinosaurs-length-difference',
      lesson: 'bnu-lower-pinecones',
      steps: [9],
      objective: ['dinosaurs', 'dinosaurs-unit'],
      manual: ['actual-dinosaurs'],
      records: [],
    },
  ],
} as const;
