export const bnuLowerCalculationReviewAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10763.html',
  checkedAt: '2026-10-05',
  unit: 'u5',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope: '74～75八原活动、43主任务与8新复习三宽已验；第六单元及整册全年继续。',
  activities: [
    {
      page: 74,
      sourceActivity: 'harvest-four-equations-and-own-method-map',
      lesson: 'bnu-lower-calculation-review',
      steps: [1, 2],
      objective: ['harvest-all', 'place-alignment', 'add-parts', 'sub-parts'],
      manual: ['actual-harvest', 'actual-map'],
      records: ['method-record'],
    },
    {
      page: 74,
      sourceActivity: 'open-problem-bank-thirty-minus-four',
      lesson: 'bnu-lower-calculation-review',
      steps: [3],
      objective: ['problem-exploration'],
      manual: ['actual-problem'],
      records: ['problem-record'],
    },
    {
      page: 74,
      sourceActivity: 'four-counter-practice-equations',
      lesson: 'bnu-lower-calculation-review',
      steps: [4],
      objective: ['counter-1', 'counter-2', 'counter-3', 'counter-4'],
      manual: ['actual-counters'],
      records: [],
    },
    {
      page: 74,
      sourceActivity: 'all-four-written-equations',
      lesson: 'bnu-lower-calculation-review',
      steps: [5],
      objective: ['written-1', 'written-2', 'written-3', 'written-4'],
      manual: ['actual-written'],
      records: [],
    },
    {
      page: 75,
      sourceActivity: 'all-eight-baskets-and-six-matches',
      lesson: 'bnu-lower-calculation-review',
      steps: [6],
      objective: ['baskets-all', 'baskets-results'],
      manual: ['actual-baskets'],
      records: [],
    },
    {
      page: 75,
      sourceActivity: 'all-six-comparisons',
      lesson: 'bnu-lower-calculation-review',
      steps: [7],
      objective: [
        'compare-1',
        'compare-2',
        'compare-3',
        'compare-4',
        'compare-5',
        'compare-6',
      ],
      manual: ['actual-comparisons'],
      records: [],
    },
    {
      page: 75,
      sourceActivity: 'four-prices-buy-two-and-shortfall-and-own-question',
      lesson: 'bnu-lower-calculation-review',
      steps: [8],
      objective: ['ball-prices', 'buy-two', 'shortfall'],
      manual: ['actual-shopping', 'actual-own-question'],
      records: ['own-question-record'],
    },
    {
      page: 75,
      sourceActivity: 'one-outfit-within-hundred-budget',
      lesson: 'bnu-lower-calculation-review',
      steps: [9, 10],
      objective: [
        'outfit',
        'outfit-example-total',
        'outfit-example-change',
        'site-zero',
      ],
      manual: ['actual-outfit'],
      records: ['reflection', 'plan'],
    },
  ],
} as const;
