/** Source-to-task correspondence for the independent classroom design practice. */
export const bnuLowerClassroomAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10760.html',
  checkedAt: '2026-10-05',
  unit: 'classroom',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '印刷24～26页综合实践所列活动及注明迁移逐项对应；不证明后续单元、全册、全年或实际合作完成。',
  activities: [
    {
      page: 24,
      sourceActivity: 'observe-four-areas',
      scope: '观察彩旗、灯笼、气球、花盆规律并说明范围',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [1],
      objective: ['unknown-rule'],
      manual: ['actual-observe'],
      records: ['observations'],
      boundary: '未明确规则的有限片段不强判唯一；不猜遮挡或原图全部数量。',
    },
    {
      page: 24,
      sourceActivity: 'represent-rule',
      scope: '用符号、画图或语言表示重复',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [2],
      objective: ['two-unit', 'two-next-7', 'two-next-8', 'two-shown'],
      manual: ['actual-symbols'],
      records: [],
      boundary: '本站两位置大/小圆六卡原创模拟，不是原灯笼写实或件数。',
    },
    {
      page: 24,
      sourceActivity: 'state-task',
      scope: '说清本次活动任务和准备做什么',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [3],
      objective: [],
      manual: ['actual-task'],
      records: [],
      boundary: '说明任务不等于已合作完成或已真正布置。',
    },
    {
      page: 25,
      sourceActivity: 'choose-place-materials',
      scope: '商量装饰地点和物品',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [3],
      objective: ['roles'],
      manual: ['actual-location'],
      records: ['design-record'],
      boundary: '独作、待商量和实际约定分工分开。',
    },
    {
      page: 25,
      sourceActivity: 'choose-repeat-unit',
      scope: '商量物品怎样重复，并说、画规则',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [4],
      objective: [
        'three-next-7',
        'three-next-8',
        'three-next-9',
        'three-unit',
        'three-circles',
        'three-types',
      ],
      manual: ['actual-rule'],
      records: [],
      boundary:
        '原两个心一花改为原创圆圆三角示例，重复同形仍占两个位置，类型与组长分开。',
    },
    {
      page: 25,
      sourceActivity: 'group-design',
      scope: '小组分工合作设计装饰图',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [3, 4],
      objective: [],
      manual: ['actual-group'],
      records: [],
      boundary:
        '真实合作独立确认，独自纸图不冒小组共同完成，不要求高处实地布置。',
    },
    {
      page: 26,
      sourceActivity: 'display-richness',
      scope: '分享各部分规则和丰富度',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [5],
      objective: ['richness'],
      manual: ['actual-display'],
      records: [],
      boundary: '允许多种设计；丰富不当无规则乱摆或高花费。',
    },
    {
      page: 26,
      sourceActivity: 'listen-and-revise',
      scope: '听取分享后提出和实际改进',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [5],
      objective: [],
      manual: ['actual-revise'],
      records: ['improvement'],
      boundary: '已听意见、已修改和未来改法分别记录，不强迫接受所有意见。',
    },
    {
      page: 26,
      sourceActivity: 'life-cycles',
      scope: '四季和生肖每12年例子及自举生活规律',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [6],
      objective: ['seasons', 'season-count', 'zodiac-years'],
      manual: ['actual-life'],
      records: [],
      boundary:
        '四季名称顺序与照片排版分开；12年不是12月/天，不保证每次天气景象相同。',
    },
    {
      page: 26,
      sourceActivity: 'three-evaluations',
      scope: '规则设计、合作、认真倾听三方面分别评价',
      lesson: 'bnu-lower-classroom-decoration',
      steps: [7],
      objective: ['evaluation'],
      manual: [
        'actual-evaluate-design',
        'actual-evaluate-cooperate',
        'actual-evaluate-listen',
      ],
      records: [
        'evaluation-design',
        'evaluation-cooperate',
        'evaluation-listen',
        'plan',
      ],
      boundary:
        '实际回顾、原话自评、帮助与未来计划独立；不自动给星或以客观正确率代评。',
    },
  ],
} as const;
