export const bnuLowerFrogsAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10763.html',
  checkedAt: '2026-10-05',
  unit: 'u5',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '66～67全部七原活动/三种加减方法/八算式/两段数线/两应用完整对应；68页起、整册全年与最终教师试用未核验。',
  activities: [
    {
      page: 66,
      sourceActivity: 'addition-three-methods',
      lesson: 'bnu-lower-frogs',
      steps: [1, 2, 3],
      objective: [
        'frog-values',
        'add-values',
        'add-sequential',
        'add-tens',
        'add-ones',
        'add-combine',
        'add-counter-digits',
        'add-beads',
      ],
      manual: [
        'actual-add-sequential',
        'actual-add-counter',
        'actual-add-place',
      ],
      records: [],
    },
    {
      page: 66,
      sourceActivity: 'comparison-three-methods',
      lesson: 'bnu-lower-frogs',
      steps: [4, 5],
      objective: [
        'sub-values',
        'sub-sequential',
        'sub-tens',
        'sub-ones',
        'sub-combine',
        'sub-counter-digits',
        'sub-beads',
        'comparison-meaning',
      ],
      manual: [
        'actual-sub-sequential',
        'actual-sub-counter',
        'actual-sub-place',
      ],
      records: [],
    },
    {
      page: 67,
      sourceActivity: 'four-calculations-and-place-discussion',
      lesson: 'bnu-lower-frogs',
      steps: [6, 10],
      objective: ['discussion-four', 'same-place', 'site-zero'],
      manual: ['actual-discussion-four', 'actual-place-explain', 'actual-own'],
      records: ['method-record', 'own-record', 'plan'],
    },
    {
      page: 67,
      sourceActivity: 'four-counter-calculations',
      lesson: 'bnu-lower-frogs',
      steps: [6],
      objective: ['counter-46', 'counter-37', 'counter-45', 'counter-56'],
      manual: [
        'actual-counter-46',
        'actual-counter-37',
        'actual-counter-45',
        'actual-counter-56',
      ],
      records: [],
    },
    {
      page: 67,
      sourceActivity: 'both-two-jump-lines',
      lesson: 'bnu-lower-frogs',
      steps: [7, 8],
      objective: [
        'line-add-points',
        'line-add-combined',
        'line-sub-points',
        'line-sub-combined',
        'line-final',
      ],
      manual: ['actual-line-add', 'actual-line-sub'],
      records: [],
    },
    {
      page: 67,
      sourceActivity: 'piano-key-parts-total',
      lesson: 'bnu-lower-frogs',
      steps: [9],
      objective: ['piano-values', 'piano-unit'],
      manual: ['actual-piano'],
      records: [],
    },
    {
      page: 67,
      sourceActivity: 'bus-departure-remaining',
      lesson: 'bnu-lower-frogs',
      steps: [9],
      objective: ['bus-values', 'bus-meaning'],
      manual: ['actual-bus'],
      records: [],
    },
  ],
} as const;
