export const bnuLowerHundredChartAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10762.html',
  checkedAt: '2026-10-05',
  unit: 'u4',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅55～56七项全部原活动及明示新条件；57页起整理复习另制作，不证明整个单元或全年。',
  activities: [
    {
      page: 55,
      sourceActivity: 'fill-full-chart',
      lesson: 'bnu-lower-hundred-chart',
      steps: [1],
      objective: [
        'row-1',
        'row-2',
        'row-3',
        'row-4',
        'row-5',
        'row-6',
        'row-7',
        'row-8',
        'row-9',
        'row-10',
        'minimum',
        'maximum',
        'given-count',
        'blank-count',
        'hundred-tens-zero',
      ],
      manual: ['actual-full-chart'],
      records: [],
      boundary:
        '保留全部给定与全部空、具体方向/范围；真实活动、开放说明和未来计划分开，不以网站评分确认实际操作。',
    },
    {
      page: 55,
      sourceActivity: 'chart-discoveries',
      lesson: 'bnu-lower-hundred-chart',
      steps: [2],
      objective: [
        'third-column',
        'right-neighbour',
        'below-neighbour',
        'row-boundary',
        'two-diagonals',
      ],
      manual: ['actual-discovery'],
      records: ['own-horizontal', 'own-vertical', 'own-diagonal'],
      boundary:
        '保留全部给定与全部空、具体方向/范围；真实活动、开放说明和未来计划分开，不以网站评分确认实际操作。',
    },
    {
      page: 55,
      sourceActivity: 'fragment-fifty-eight',
      lesson: 'bnu-lower-hundred-chart',
      steps: [3],
      objective: ['fragment-58', 'fragment-58-centre'],
      manual: ['actual-fragment-58'],
      records: [],
      boundary:
        '保留全部给定与全部空、具体方向/范围；真实活动、开放说明和未来计划分开，不以网站评分确认实际操作。',
    },
    {
      page: 56,
      sourceActivity: 'fragment-sixty-seven',
      lesson: 'bnu-lower-hundred-chart',
      steps: [4],
      objective: ['fragment-67', 'fragment-67-neighbours'],
      manual: ['actual-fragment-67'],
      records: [],
      boundary:
        '保留全部给定与全部空、具体方向/范围；真实活动、开放说明和未来计划分开，不以网站评分确认实际操作。',
    },
    {
      page: 56,
      sourceActivity: 'four-colour-rules',
      lesson: 'bnu-lower-hundred-chart',
      steps: [5],
      objective: [
        'ones-zero',
        'ones-seven',
        'equal-digits-full',
        'equal-digits-two',
        'ones-one-less',
        'colour-overlap',
      ],
      manual: [
        'actual-green',
        'actual-blue',
        'actual-yellow',
        'actual-red',
        'actual-colour-explain',
      ],
      records: ['own-colour'],
      boundary:
        '保留全部给定与全部空、具体方向/范围；真实活动、开放说明和未来计划分开，不以网站评分确认实际操作。',
    },
    {
      page: 56,
      sourceActivity: 'two-number-lines',
      lesson: 'bnu-lower-hundred-chart',
      steps: [6],
      objective: ['line-two', 'line-ten'],
      manual: ['actual-line-two', 'actual-line-ten'],
      records: [],
      boundary:
        '保留全部给定与全部空、具体方向/范围；真实活动、开放说明和未来计划分开，不以网站评分确认实际操作。',
    },
    {
      page: 56,
      sourceActivity: 'three-chart-fragments',
      lesson: 'bnu-lower-hundred-chart',
      steps: [7, 8],
      objective: ['practice-one', 'practice-two', 'practice-three'],
      manual: [
        'actual-practice-one',
        'actual-practice-two',
        'actual-practice-three',
        'actual-fragment-explain',
      ],
      records: ['difficulty', 'plan'],
      boundary:
        '保留全部给定与全部空、具体方向/范围；真实活动、开放说明和未来计划分开，不以网站评分确认实际操作。',
    },
  ],
} as const;
