/** Printed pages 31–32 source activity correspondence. */
export const bnuLowerComplementAudit = {
  resourceId: 'bnu-lower-public-scan-2024',
  source: 'https://keben.szxuexiao.com/html/10761.html',
  checkedAt: '2026-10-05',
  unit: 'u3',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  scope:
    '仅印刷31～32页凑数游戏原活动与明示迁移，33页起仍待制作，不证明整单元、全册或全年。',
  activities: [
    {
      page: 31,
      sourceActivity: 'game',
      scope: '两人两轮凑14与自由填数',
      lesson: 'bnu-lower-complement-game',
      steps: [1],
      objective: ['partner-six', 'partner-five', 'partner-seven', 'free-pair'],
      manual: ['actual-game'],
      records: [],
      boundary: '两人各出7可合法，0～14范围是本站补充，不冒原卡片。',
    },
    {
      page: 31,
      sourceActivity: 'break-ten',
      scope: '原14拆10与4',
      lesson: 'bnu-lower-complement-game',
      steps: [2],
      objective: ['break-ten'],
      manual: ['actual-break'],
      records: [],
      boundary: '拆原数，不把其它正确路径当错。',
    },
    {
      page: 31,
      sourceActivity: 'methods',
      scope: '拆5与两跳及想加算减',
      lesson: 'bnu-lower-complement-game',
      steps: [3],
      objective: ['parts', 'line', 'think-add'],
      manual: ['actual-parts', 'actual-line'],
      records: [],
      boundary: '先减4到10再1，图左−1不是先做。',
    },
    {
      page: 31,
      sourceActivity: 'records',
      scope: '记录原五轮加减式',
      lesson: 'bnu-lower-complement-game',
      steps: [4],
      objective: ['record-0', 'record-1', 'record-2', 'record-3', 'record-4'],
      manual: ['actual-records'],
      records: [],
      boundary: '每轮分别记录，真实合作不由网页确认。',
    },
    {
      page: 32,
      sourceActivity: 'sorted-change',
      scope: '按减数排序、发现与续写',
      lesson: 'bnu-lower-complement-game',
      steps: [4, 5],
      objective: ['sorted', 'fixed-fourteen', 'extend-ten', 'extend-eleven'],
      manual: ['actual-extend'],
      records: [],
      boundary: '原14固定才每次多减1少1，不推广所有算式。',
    },
    {
      page: 32,
      sourceActivity: 'practice-one',
      scope: '原四题分解与说法',
      lesson: 'bnu-lower-complement-game',
      steps: [6],
      objective: [
        'decompose-0',
        'method-0',
        'decompose-1',
        'method-1',
        'decompose-2',
        'method-2',
        'decompose-3',
        'method-3',
      ],
      manual: ['actual-decompose'],
      records: [],
      boundary: '原箭头在原数，自由分解与指定破十路径分开，合对不证明已解释。',
    },
    {
      page: 32,
      sourceActivity: 'practice-two',
      scope: '原三列全部九式与规律',
      lesson: 'bnu-lower-complement-game',
      steps: [7],
      objective: [
        'column-0',
        'column-1',
        'column-2',
        'column-3',
        'column-4',
        'column-5',
        'column-6',
        'column-7',
        'column-8',
        'column-one',
        'column-three',
      ],
      manual: ['actual-columns'],
      records: [],
      boundary: '固定减数与固定原数的方向不同。',
    },
    {
      page: 32,
      sourceActivity: 'practice-three',
      scope: '前后小鸭与苹果未知量',
      lesson: 'bnu-lower-complement-game',
      steps: [8],
      objective: [
        'ducks-original',
        'ducks-outside',
        'ducks-hidden',
        'ducks-unknown',
        'apples-taken',
        'apples-eight',
      ],
      manual: ['actual-pictures'],
      records: [],
      boundary:
        '同群11无增减、草丛外8才求内3；局部头不加到外部，不把15余8当拿走8。',
    },
    {
      page: 32,
      sourceActivity: 'explain',
      scope: '方法表达与本站反思计划',
      lesson: 'bnu-lower-complement-game',
      steps: [9],
      objective: [],
      manual: ['actual-explain'],
      records: ['discovery', 'difficulty', 'plan'],
      boundary: '实做、发现、困惑与计划独立，不评分。',
    },
  ],
} as const;
