import type { Volume } from '../learning/types';

/** Factual teaching scope, keyed to the verified official lesson directory.
 * Lists do not reproduce textbook prose, illustrations or page layouts.
 * Additional contextual readings are separate from the count of newly introduced characters.
 */
export interface CharacterScope {
  recognize: string;
  write: string;
  writeVerified: boolean;
  additionalReadings?: string;
}
type Row = [
  id: string,
  recognize: string,
  write: string,
  additionalReadings?: string,
];
function scopes(
  rows: Row[],
  writeVerified = true,
): Record<string, CharacterScope> {
  return Object.fromEntries(
    rows.map(([id, recognize, write, additionalReadings]) => [
      id,
      {
        recognize,
        write,
        additionalReadings,
        writeVerified: writeVerified || write.length > 0,
      },
    ]),
  );
}

export const upperCharacters = scopes([
  ['u1-1', '天地人你我他', ''],
  ['u1-2', '一二三四五上下', '一二三上'],
  ['u1-3', '口耳目手足站坐', '口耳目手'],
  ['u1-4', '日月山川水火田禾', '日火田禾'],
  ['u1-5', '六七八九十', '六七八十'],
  ['u2-3', '爸妈', ''],
  ['u2-4', '大马路土', ''],
  ['u2-5', '本学校班级姓名王', '九王'],
  ['u3-1', '哥弟画花', ''],
  ['u3-2', '打棋积木', ''],
  ['u3-3', '字词句子', ''],
  ['u3-4', '桌纸读书', ''],
  ['u3-5', '鱼鸭乌鸦', ''],
  ['u3-6', '午星期语文数写会', '午下'],
  ['u4-1', '白菜西瓜果', ''],
  ['u4-2', '小桥流柳', ''],
  ['u4-3', '开雪夜色美', ''],
  ['u4-4', '蓝云草原', ''],
  ['u4-5', '冰自行车', ''],
  ['u4-6', '晚昨今明个这去年', '个去'],
  ['u5-1', '秋气了树叶黄片从来飞', '了子大人'],
  ['u5-2', '江南可采莲戏间东北', '可叶东西'],
  ['u5-3', '的家鸡竹牙用几步没参加', '竹马牙用几'],
  ['u5-4', '鸟说是春青蛙夏着皮就冬', '四小鸟是天', '地'],
  ['u5-5', '男女关正反先后内外', '女开关先'],
  ['u6-1', '对歌雨风虫清绿桃红', '云雨虫山水'],
  ['u6-2', '力尖尘众双林森不条心金', '力男土木心'],
  ['u6-3', '包尺作业笔刀宝贝少课早', '尺本刀不少'],
  ['u6-4', '升国旗中们声起多么向立', '中五风立正'],
  ['u6-5', '老师工厂医院生门卫', '工厂门卫'],
  ['u7-1', '船弯儿两头在里看见闪', '月儿头里见'],
  ['u7-2', '影前常黑狗左右它好朋友', '在我左右'],
  ['u7-3', '件有和做也办到又才能', '和也又才'],
  ['u7-4', '爷奶叔姐妹', '爸妈'],
  ['u8-1', '比尾巴谁长短把伞兔最公', '比巴长公'],
  ['u8-2', '喝只处找许石出法放进高', '只多办石出', '着'],
  ['u8-3', '点彩半空问回答方久更', '来半你有', '数长'],
  ['u8-4', '牛羊爪元拼音', '牛羊爪白'],
]);

/** Lower recognition pages 114–116 and all writing pages 117–119 were rechecked
 * against the third-party public preview on 2026-10-01. Lesson-body checks remain
 * separate provenance. Scope updates do not rewrite stored historical questions.
 */
export const lowerCharacters = scopes(
  [
    ['u1-1', '霜吹落降飘游池入', '春冬吹花飞入'],
    ['u1-2', '氏什李张弓古胡吴言孙', '什么古胡双言'],
    ['u1-3', '河晴眼睛保护苗吃事情请让', '青清晴苗请生'],
    ['u1-4', '猜边凉喜欢时怕攻令感动万无', '字红动万无明'],
    ['u1-5', '识组计算减式图形卡合唱团', '文卡片合'],
    ['u2-1', '热爱共产党太阳光怀抱幸福成', '共产党太阳光'],
    ['u2-2', '井城村毛主席住乡亲战士想念', '井江方主住后'],
    ['u2-3', '告诉走京座安广场非宽丽洁', '告会京的北广'],
    ['u2-4', '认连选圈涂填试练', '写认'],
    ['u3-1', '玩得急直哭跟忽然听喊快己背', '走说自河让己'],
    ['u3-2', '很孤单种每都邻居叫招呼乐', '从们他好叫回', '只'],
    ['u3-3', '怎独跳绳当还羽球劲轮排', '快当画乐书毛', '乐得'],
    ['u3-4', '母页止斤寸丁千全元', '止斤寸丁千元'],
    ['u4-1', '静思床疑举望低故', '思床前地故乡'],
    ['u4-2', '胆敢勇讲窗乱拉样笑再睡觉', '色把讲样笑再'],
    ['u4-3', '端粽节总煮盼米枣甜分鲜肉', '节米间分吃肉', '了'],
    ['u4-4', '册支台电视部机衣裤被', '册支电衣'],
    ['u5-1', '物捉迷藏造蚂蚁运食粮房结网', '物造运欢房网'],
    ['u5-2', '圆严寒酷暑暖晨细朝霞夕杨香', '对今雪细夕语'],
    ['u5-3', '操拔拍跑踢铃真闹丢沙身体', '打皮跑足沙包'],
    ['u5-4', '之初相近习远教道专幼玉知义', '近习远学玉义'],
    ['u5-5', '饭饱茶泡轻穿袍鞭炮', '饱抱'],
    ['u6-1', '诗首偷浮萍泉惜照柔荷露角', '首池采尖角早'],
    ['u6-2', '浪迈悄泪次给壳虾装像淘娃', '玩眼泪它贝气'],
    ['u6-3', '珠摇篮亮晶停坪展透翅膀朵', '机台唱伞朵美'],
    ['u6-4', '要腰阴沉呀忙呢吗面闷吧消息', '这看鱼面问加', '空'],
    ['u6-5', '棍豆汤蚊扇椅牵织斗', '豆斗'],
    ['u7-1', '具铅新平盒些此仔检查所伙伴', '笔知道放平安'],
    ['u7-2', '钟迟灯等啊决定已经位表', '灯车站课坐老师', '背'],
    ['u7-3', '虎熊通注意遍百为因舌理忘第', '国都百听时点林', '呀'],
    ['u7-4', '猴块兴掰扛往棵满扔摘捧追', '高兴着往瓜兔进', '结'],
    ['u7-5', '刷梳巾皂洗澡脸盆', '巾洗'],
    ['u8-1', '棉姑娘病她治燕帮害别干惊奇', '她空还干身星久'],
    ['u8-2', '咕咚熟掉湖吓啦鹿象野拦哪那领', '吓为怕家象没到'],
    ['u8-3', '壁借咬难爬您拨赶摆过孩转', '向边行草赶过找', '哪'],
    ['u8-4', '吵现顶胖票户交父', '页户交父'],
  ],
  false,
);

export function characterScopes(volume: Volume) {
  return volume === 'upper' ? upperCharacters : lowerCharacters;
}

export const strokeNames = [
  '横',
  '竖',
  '撇',
  '点',
  '捺',
  '提',
  '横折',
  '横撇',
  '横钩',
  '竖折',
  '竖弯',
  '竖提',
  '竖钩',
  '撇折',
  '撇点',
  '弯钩',
  '斜钩',
  '卧钩',
  '横折折',
  '横折弯',
  '横折提',
  '横折钩',
  '横斜钩',
  '竖折折',
  '竖折撇',
  '竖弯钩',
  '横折折折',
  '横折折撇',
  '横折弯钩',
  '横撇弯钩',
  '竖折折钩',
  '横折折折钩',
];

export const upperRadicals = [
  '单人旁',
  '八字头',
  '人字头',
  '斜刀头',
  '包字头',
  '倒八',
  '言字旁',
  '双耳旁',
  '提土旁',
  '提手旁',
  '草字头',
  '口字旁',
  '国字框',
  '三撇',
  '反犬旁',
  '折文',
  '门字框',
  '三点水',
  '宝盖头',
  '走之底',
  '女字旁',
  '绞丝旁',
  '木字旁',
  '日字旁',
  '月字旁',
  '四点底',
  '禾字旁',
  '穴字头',
  '竹字头',
];
export const lowerRadicals = [
  '立刀旁',
  '京字头',
  '两点水',
  '力字旁',
  '又字旁',
  '大字头',
  '双人旁',
  '食字旁',
  '广字头',
  '竖心旁',
  '尸字头',
  '弓字旁',
  '子字旁',
  '王字旁',
  '车字旁',
  '牛字旁',
  '反文旁',
  '爪字头',
  '火字旁',
  '户字头',
  '示字旁',
  '心字底',
  '目字旁',
  '皿字底',
  '金字旁',
  '病字头',
  '衣字旁',
  '页字旁',
  '虫字旁',
  '舌字旁',
  '米字旁',
  '走字底',
  '足字旁',
  '雨字头',
];

export const characterSources = {
  upper: {
    resourceId: '1211001101241',
    recognizePages: [105, 106, 107],
    writePages: [108],
    referencePages: [109, 110],
    strokePages: [109],
    radicalPages: [110],
    reviewedAt: '2026-09-30',
  },
  lower: {
    resourceId: '1211001102241',
    recognizePages: [114, 115, 116],
    writePages: [117, 118, 119],
    pendingWritePages: [] as number[],
    tableSource: {
      url: 'https://keben.app/book/0026',
      provider: '第三方原书公开预览',
      checkedAt: '2026-10-01',
      pages: [114, 115, 116, 117, 118, 119],
    },
    verifiedWritingLessonPages: {
      'u1-1': 3,
      'u1-2': 5,
      'u1-3': 7,
      'u1-4': 9,
      'u1-5': 10,
      'u2-1': 17,
      'u2-2': 19,
      'u2-3': 21,
      'u2-4': 22,
    },
    writingLessonSource: {
      url: 'https://keben.app/book/0026',
      provider: '第三方原书公开预览',
      checkedAt: '2026-10-01',
    },
    referencePages: [120],
    strokePages: [],
    radicalPages: [120],
    reviewedAt: '2026-09-30',
  },
};
