/** This audit distinguishes inspected source pages, existing tasks and unresolved activity gaps. */
export const sujiaoFinalUnitAudit = {
  isbn: '978-7-5743-1295-1',
  checkedAt: '2026-10-02',
  unit: 'review',
  status: 'original-teaching-implemented',
  finalTeacherReview: 'not-verified',
  pages: [
    {
      page: 88,
      scope: '学期回顾、数分类、数序、开区间与各数组成',
      evidence: [
        [
          'sj-lower-final-numbers-shapes',
          [
            'all-between',
            'composition-0',
            'composition-1',
            'composition-2',
            'composition-3',
            'composition-4',
            'composition-5',
            'composition-6',
            'composition-7',
            'composition-8',
            'endpoints',
            'manual-0',
          ],
        ],
        [
          'sj-lower-final-numbers',
          [
            'category',
            'next',
            'gaps',
            'between',
            'composition',
            'manual-0',
            'manual-1',
            'manual-2',
          ],
        ],
        [
          'sj-lower-final-classification-review',
          [
            'evaluation-numbers',
            'evaluation-calculation',
            'evaluation-classification',
            'evaluation-strength',
            'evaluation-new-question',
          ],
        ],
      ],
      boundary:
        '原创区间；新增自主列全九数并逐数组成的实际任务，不能由旧候选选数或一个组成题替代。',
    },
    {
      page: 89,
      scope: '运算分类、四种数量关系、五类图形、同样两片拼组与四向字典观察',
      evidence: [
        [
          'sj-lower-final-numbers-shapes',
          [
            'name-0',
            'name-1',
            'name-2',
            'name-3',
            'name-4',
            'join-0',
            'join-1',
            'join-2',
            'same-dictionary',
            'views-not-fixed',
            'manual-1',
            'manual-2',
            'manual-3',
            'manual-4',
            'manual-5',
          ],
        ],
        [
          'sj-lower-final-numbers',
          ['add-units', 'subtract-units', 'classify', 'manual-3'],
        ],
        [
          'sj-lower-final-relations',
          [
            'more-difference',
            'less-difference',
            'target-more',
            'target-less',
            'scope',
            'manual-0',
          ],
        ],
        [
          'sj-lower-final-classification-review',
          ['evaluation-shapes', 'evaluation-observation'],
        ],
      ],
      boundary:
        '五类实际口头命名、三种两片同形纸片实际拼组及同一本字典四向观察独立确认；示例比例限定，不强求实物观察四图各异，依次换位如实记。',
    },
    {
      page: 90,
      scope: '标志按标准分类、每五每十数书、拨珠组成及直线上表示排序',
      evidence: [
        [
          'sj-lower-final-counting',
          [
            'groups-5',
            'books-5',
            'groups-10',
            'books-10',
            'five-accumulation',
            'ten-accumulation',
            'six-points',
            'ordered-points',
            'point-range',
            'interval-count',
            'regroup-total',
            'unknown-not-zero',
            'manual-0',
            'manual-1',
            'manual-2',
            'manual-3',
          ],
        ],
        [
          'sj-lower-final-classification-review',
          [
            'sign-triangle',
            'sign-circle',
            'sign-rectangle',
            'sign-blue',
            'sign-count-0',
            'sign-count-1',
            'sign-count-2',
            'manual-0',
          ],
        ],
        [
          'sj-lower-final-numbers',
          ['read', 'composition', 'beads', 'zero', 'order', 'manual-1'],
        ],
      ],
      boundary:
        '原创外形卡不教道路含义；教材原图实际分类另记录。同一批实物按五本十本重分记录，真实余数另记；纸面六数先标点再排序独立确认，不由网页读点或排序成绩替代。',
    },
    {
      page: 91,
      scope: '相对数量找对应、加减小表与相等算式、单位计算、口算及桌椅缺额',
      evidence: [
        [
          'sj-lower-final-data-questions',
          [
            'joint-reading',
            'relative-not-equal',
            'relative-no-threshold',
            'manual-0',
          ],
        ],
        [
          'sj-lower-final-numbers',
          [
            'add-units',
            'subtract-units',
            'carry',
            'borrow',
            'small-add',
            'small-subtract',
            'manual-2',
            'manual-3',
          ],
        ],
        ['sj-lower-final-relations', ['shortages', 'manual-3']],
        [
          'sj-lower-final-equations',
          [
            'table-add',
            'table-subtract',
            'equal-add',
            'equal-subtract',
            'manual-0',
            'manual-1',
            'manual-2',
          ],
        ],
      ],
      boundary:
        '两张原创小表分别填写，并实际自主写等值算式；减法为列头减行头，不搬用其它表格规则。原创四人描述联合配对另有实际卡片与换数核对；相对用语不规定固定差值。',
    },
    {
      page: 92,
      scope: '按差求量、比较跳绳表与自主提问、抓物提问、十二棒围图及两种折剪拼',
      evidence: [
        [
          'sj-lower-final-data-questions',
          [
            'jump-rain-sun',
            'jump-sun-wind',
            'jump-rain-wind',
            'jump-data-limit',
            'objects-total',
            'objects-difference',
            'question-conditions',
            'own-question-record',
            'manual-1',
            'manual-2',
            'manual-3',
          ],
        ],
        [
          'sj-lower-final-relations',
          ['target-more', 'more-difference', 'less-difference', 'manual-0'],
        ],
        [
          'sj-lower-twelve-sticks',
          [
            'sticks-0',
            'sides-0',
            'horizontal-vertical',
            'circle',
            'methods',
            'manual-0',
            'manual-1',
            'manual-2',
            'manual-3',
          ],
        ],
        [
          'sj-lower-fold-cut-join',
          [
            'folded-0',
            'pieces-0',
            'a-sides-0',
            'shape-0',
            'folded-1',
            'pieces-1',
            'a-sides-1',
            'shape-1',
            'cut-end',
            'manual-0',
            'manual-1',
            'manual-2',
            'manual-3',
          ],
        ],
      ],
      boundary:
        '围图与剪线示例原创且实际另确认；三人不同配对及两组已知量自主提问、解答、交流分别人工记录，固定题正确不替代自主活动。',
    },
    {
      page: 93,
      scope:
        '无拼缝按三角单位计数和找其它图形、花车时序、两柜分类、三班同时安排',
      evidence: [
        [
          'sj-lower-final-embedded',
          [
            'count-0',
            'count-1',
            'count-2',
            'outline-0',
            'outline-1',
            'outline-2',
            'outline-3',
            'outline-4',
            'outline-5',
            'internal',
            'different-size',
            'actual-work',
            'manual-0',
            'manual-1',
            'manual-2',
            'manual-3',
          ],
        ],
        [
          'sj-lower-final-parade',
          [
            'order',
            'first',
            'last',
            'beside',
            'distance-only',
            'same-drawing-size',
            'speed',
            'changed-observer',
            'one-float',
            'real-task',
            'manual-0',
            'manual-1',
            'manual-2',
            'manual-3',
          ],
        ],
        [
          'sj-lower-triangle-mosaics',
          ['count-0', 'count-1', 'count-2', 'count-3', 'manual-2'],
        ],
        [
          'sj-lower-final-classification-review',
          [
            'clothes-upper',
            'clothes-red',
            'clothes-count',
            'conserve',
            'unknown',
            'manual-1',
            'manual-2',
          ],
        ],
        [
          'sj-lower-final-relations',
          ['class-totals', 'assign', 'alone', 'reuse', 'manual-1', 'manual-2'],
        ],
      ],
      boundary:
        '新增三原创图分别计数与大小轮廓实际描画，教材原三图另人工观察；花车侧面原创模型与教材原图观察分别记录，同一物体、固定参照与方向不由编号或距离替代。真实人数和教室容量不补造。',
    },
    {
      page: 94,
      scope: '两边算式相等求符号、附片拼四类、数学连环画、共同标准差和七项评价',
      evidence: [
        [
          'sj-lower-final-four-shapes',
          [
            'whole-0',
            'whole-1',
            'whole-2',
            'circle-complete',
            'missing-piece',
            'piece-count',
            'outer-straight',
            'select-curved',
            'kit-total',
            'matched-material',
            'straight-circle',
            'real-record',
            'manual-0',
            'manual-1',
            'manual-2',
            'manual-3',
            'manual-4',
          ],
        ],
        [
          'sj-lower-final-equations',
          [
            'left-unknown',
            'right-unknown',
            'missing-subtrahend',
            'zero-unknown',
            'whole-number',
            'equal-meaning',
            'check-candidate',
            'keep-operation',
            'manual-3',
          ],
        ],
        [
          'sj-lower-final-relations',
          ['same-reference', 'reference-difference', 'manual-3'],
        ],
        [
          'sj-lower-math-comic',
          [
            'manual-0',
            'manual-1',
            'manual-2',
            'manual-3',
            'manual-4',
            'manual-5',
          ],
        ],
        [
          'sj-lower-final-classification-review',
          [
            'evaluation-numbers',
            'evaluation-calculation',
            'evaluation-relations',
            'evaluation-shapes',
            'evaluation-observation',
            'evaluation-classification',
            'evaluation-engagement',
            'evaluation-strength',
            'evaluation-new-question',
            'manual-2',
          ],
        ],
      ],
      boundary:
        '七项评价各自null不自动星级；等式符号表示整个数，试填后代回两边核对；四目标的材料准备与实际拼组独立确认，教材附页/原创替代如实记；圆由匹配曲边片围合，有限直边或缺片图不当完整圆。',
    },
  ],
  resolvedGaps: [
    {
      pages: [88, 89],
      activity: '列全开区间各数组成、三种两片实物拼组及四向字典观察',
      evidence: ['sj-lower-final-numbers-shapes'],
    },
    {
      pages: [90],
      activity: '同批书按五本十本数、六数纸面先标点再排序',
      evidence: ['sj-lower-final-counting'],
    },
    {
      pages: [91, 94],
      activity: '加减小表、自主等值算式与整数量符号',
      evidence: ['sj-lower-final-equations'],
    },
    {
      pages: [91, 92],
      activity: '四人联合配对、三人不同配对与两组已知量自主提问解答交流',
      evidence: ['sj-lower-final-data-questions'],
    },
    {
      pages: [93],
      activity: '三幅原创图单位计数、大小完整轮廓描画及教材原图另观察',
      evidence: ['sj-lower-final-embedded'],
    },
    {
      pages: [93],
      activity: '同一花车时序、实际换向记录与教材原图另观察',
      evidence: ['sj-lower-final-parade'],
    },
    {
      pages: [94],
      activity: '选四目标、匹配曲边拼圆及各目标实际操作',
      evidence: ['sj-lower-final-four-shapes'],
    },
  ],
  gaps: [],
} as const;
